// content/cats/presets-text/en.ts
import type { CatTextPreset } from "../index";
export const CAT_TEXT_PRESETS_EN: CatTextPreset[] = [
  {
    id: "friendship-en-001",
    lang: "en",
    prompt: "What is friendship?",
    texts: [
      "Meow! Let me tell you what friendship is.",
      "Friendship is when someone is glad to see you.",
      "You can be quiet together and it feels okay.",
      "Friends listen, even when you talk a lot.",
      "They share snacks. Even the tasty ones.",
      "Friends help when something is hard.",
      "They do not laugh when you make a mistake.",
      "You can be yourself and not pretend.",
      "Sometimes friends argue, like cats do.",
      "But they come back and stay together.",
      "That is friendship. Warm and real. Meow.",
    ],
  },

  {
    id: "dreams-en-002",
    lang: "en",
    prompt: "Why do people need dreams?",
    texts: [
      "Meow! Let’s talk about dreams.",
      "Dreams are things you want to do or become.",
      "They live inside your head like little stars.",
      "Dreams help you move forward.",
      "They say: try again, even if it is hard.",
      "With dreams, boring days feel brighter.",
      "Dreams help you choose a path.",
      "They whisper: this is important to you.",
      "Sometimes dreams change. That is okay.",
      "The main thing is to have them.",
      "Dreams make people alive inside. Meow.",
    ],
  },

  {
    id: "crying-en-003",
    lang: "en",
    prompt: "Why do we sometimes want to cry?",
    texts: [
      "Meow! Crying is not a bad thing.",
      "Sometimes feelings get too big inside.",
      "They bump into each other like kittens.",
      "Crying helps let them out.",
      "Tears are like a release button.",
      "After crying, breathing feels easier.",
      "Your heart feels a bit lighter.",
      "Even brave people cry.",
      "Even cats cry. Inside.",
      "Crying means you feel deeply.",
      "And that is okay. Meow.",
    ],
  },
{
    id: "friendship-en-001",
    lang: "en",
    prompt: "What is friendship?",
    texts: [
      "Meow! Now the cats will explain friendship.",
      "Friendship is when someone kind is close to you.",
      "With a friend, you can laugh for no big reason.",
      "Friends share toys, thoughts, and cookies.",
      "If you feel sad, a friend sits near you.",
      "Friends help each other, even when it is scary.",
      "Sometimes friends argue, but they make up.",
      "A real friend does not laugh when you are hurt.",
      "Friendship makes an ordinary day better.",
      "Even cats feel happier when they are not alone.",
      "That is friendship, meow."
    ],
  },
  {
    id: "dreams-en-001",
    lang: "en",
    prompt: "Why do people have dreams?",
    texts: [
      "Meow! Now the cats will talk about dreams.",
      "Dreams are pictures in your mind about the future.",
      "They show who you want to become.",
      "Dreams help you move forward, even when it is hard.",
      "When you dream, a spark lights up inside.",
      "Dreams make the world more interesting.",
      "Some dreams are big, some are small.",
      "Even a small dream can bring joy.",
      "Dreams help you not give up.",
      "Cats dream too, maybe about tasty fish.",
      "That is why dreams matter, meow."
    ],
  },
  {
    id: "crying-en-001",
    lang: "en",
    prompt: "Why do we sometimes feel like crying?",
    texts: [
      "Meow! Now the cats will talk about tears.",
      "Sometimes there are too many feelings inside.",
      "Tears help those feelings come out.",
      "Crying is not bad or shameful.",
      "After crying, it often feels lighter.",
      "Tears help the heart and body rest.",
      "Sometimes we cry from sadness.",
      "Sometimes from hurt or tiredness.",
      "And sometimes even from joy.",
      "After tears, calm often comes.",
      "Cats also feel sad sometimes.",
      "Crying is normal, meow."
    ],
  },
  {
    id: "happiness-en-001",
    lang: "en",
    prompt: "How do you know you are happy?",
    texts: [
      "Meow! Cats know what happiness looks like.",
      "Happiness is not always loud or shiny.",
      "Sometimes it is a warm feeling inside.",
      "You wake up and do not want to run from the day.",
      "You like being yourself.",
      "Small joys feel important.",
      "You can laugh without a big reason.",
      "You are not afraid to feel sad sometimes.",
      "It feels safe to be near someone.",
      "Or safe even when you are alone.",
      "When it is calm and bright inside, that is happiness, meow."
    ],
  },
  {
    id: "adult-en-001",
    lang: "en",
    prompt: "What does it mean to be an adult?",
    texts: [
      "Meow! Being an adult is not just about age.",
      "It is not only about looking serious.",
      "Being grown up means taking responsibility.",
      "It means saying, I was wrong.",
      "It means fixing your mistakes.",
      "It means waiting, even when you want it now.",
      "It means caring about others too.",
      "It means thinking before you act.",
      "Adults can still play and laugh.",
      "Being grown up does not mean being boring.",
      "It means keeping balance, meow."
    ],
  },
  {
    id: "boredom-en-001",
    lang: "en",
    prompt: "Why do we get bored?",
    texts: [
      "Meow! Boredom is also a feeling.",
      "It comes when nothing seems to happen.",
      "Or when everything feels the same.",
      "The brain wants something new.",
      "It starts looking for excitement.",
      "Boredom pushes us to invent games.",
      "Many ideas are born from boredom.",
      "It says, I want something different.",
      "It is like a cat tired of lying still.",
      "The cat stands up and explores.",
      "Boredom can start an adventure, meow."
    ],
  },
  {
    id: "good-and-evil-en-001",
    lang: "en",
    prompt: "How can we tell good from evil?",
    texts: [
      "Meow! This is a big question.",
      "Good makes the world warmer.",
      "Evil causes pain.",
      "If someone feels better after your action, it is likely good.",
      "If someone feels worse, think again.",
      "Good respects other people's feelings.",
      "Evil thinks only about itself.",
      "Good helps.",
      "Evil harms.",
      "Sometimes it is hard to tell.",
      "Listen to your heart and mind together.",
      "They usually know, meow."
    ],
  },
  {
  id: "forgiveness-en-001",
  lang: "en",
  prompt: "Why is it important to forgive?",
  texts: [
    "Meow! Forgiving does not mean forgetting.",
    "Forgiving means letting go of a heavy stone inside.",
    "When you stay angry, it feels tight inside.",
    "Hurt feelings take up space.",
    "Forgiveness gives that space back.",
    "You are not saying the bad thing was okay.",
    "You are choosing not to carry it anymore.",
    "When you forgive, you feel lighter.",
    "Sometimes it is hard.",
    "But after forgiving, breathing feels easier.",
    "Forgiveness is a gift to yourself, meow."
  ],
},
{
  id: "smart-and-kind-en-001",
  lang: "en",
  prompt: "Can you be smart and kind at the same time?",
  texts: [
    "Meow! Of course you can.",
    "Being smart means understanding the world.",
    "Being kind means caring about others.",
    "Smart without kindness can become cold.",
    "Kind without thinking can be naive.",
    "Together they become strong.",
    "Smart helps you choose the right words.",
    "Kindness helps you choose gentle words.",
    "The strongest people are smart and kind.",
    "They are not opposites.",
    "They are best friends, meow."
  ],
},
{
  id: "intuition-en-001",
  lang: "en",
  prompt: "What is intuition?",
  texts: [
    "Meow! Intuition is a quiet voice inside.",
    "It does not shout.",
    "It softly suggests something.",
    "Sometimes you just feel what is right.",
    "Your brain uses past experience very fast.",
    "So fast that you do not notice.",
    "Intuition is like a cat's instinct.",
    "It can warn you about danger.",
    "Or help you choose wisely.",
    "Sometimes it makes mistakes.",
    "That is why you listen with your mind too, meow."
  ],
},
{
  id: "twinkling-stars-en-001",
  lang: "en",
  prompt: "Why do stars twinkle?",
  texts: [
    "Meow! Stars do not blink by themselves.",
    "They shine steadily.",
    "But there is air between us and the stars.",
    "Air moves and shakes.",
    "Light travels through that moving air.",
    "It bends a little.",
    "So the star looks like it is blinking.",
    "It is like looking through water.",
    "The star is calm.",
    "The air is playing with its light.",
    "That is why stars twinkle, meow."
  ],
},
{
  id: "stars-born-en-001",
  lang: "en",
  prompt: "How are stars born?",
  texts: [
    "Meow! Stars were once tiny too.",
    "In space there are huge clouds of gas and dust.",
    "They are called nebulae.",
    "Sometimes a part of the cloud starts to shrink.",
    "The gas gathers into a ball.",
    "It gets hotter and hotter.",
    "When it becomes very hot inside, it lights up.",
    "That is how a new star is born.",
    "It can shine for millions of years.",
    "Planets may form around it.",
    "That is how new suns appear in space, meow."
  ],
},
{
  id: "milky-way-en-001",
  lang: "en",
  prompt: "What is the Milky Way?",
  texts: [
    "Meow! The Milky Way is a huge home for stars.",
    "It is the galaxy where our Sun lives.",
    "It has billions of stars.",
    "They move around a common center.",
    "From Earth it looks like a bright stripe.",
    "That is why it is called the Milky Way.",
    "We live on one small planet inside it.",
    "Our solar system is just a tiny part.",
    "There are many other galaxies.",
    "But the Milky Way is our space home.",
    "Big, beautiful, and a little mysterious, meow."
  ],
},
{
  id: "life-other-planets-en-001",
  lang: "en",
  prompt: "Is there life on other planets?",
  texts: [
    "Meow! Scientists do not know yet.",
    "There are many planets in the universe.",
    "Some look a bit like Earth.",
    "They might have water.",
    "Where there is water, life may exist.",
    "But we have not found real aliens yet.",
    "We are still searching for signs.",
    "Life could be very far away.",
    "Or maybe we just cannot see it yet.",
    "Space is huge.",
    "So the answer for now is: maybe, meow."
  ],
},
{
  id: "moon-phases-en-001",
  lang: "en",
  prompt: "Why does the Moon change shape?",
  texts: [
    "Meow! The Moon does not really change shape.",
    "It is always round.",
    "But we see different parts of it.",
    "The Sun lights up the Moon.",
    "The Earth and Moon keep moving.",
    "Sometimes we see the whole bright side.",
    "Sometimes only half.",
    "Sometimes just a thin crescent.",
    "These are called Moon phases.",
    "The Moon just turns in a different position.",
    "That is why it looks like it changes shape, meow."
  ],
},
{
  id: "telescope-en-001",
  lang: "en",
  prompt: "How does a telescope work?",
  texts: [
    "Meow! A telescope is like an eye that sees very far.",
    "It collects light from faraway stars.",
    "Even very tiny light.",
    "Inside there are special lenses or mirrors.",
    "They make the picture bigger.",
    "Like a magnifying glass, but stronger.",
    "The bigger the telescope, the more light it catches.",
    "That is why we can see what our eyes cannot.",
    "Through a telescope we can see planets and galaxies.",
    "It helps scientists study space.",
    "That is how a telescope brings far worlds closer, meow."
  ],
},
{
  id: "comet-inside-en-001",
  lang: "en",
  prompt: "What is inside a comet?",
  texts: [
    "Meow! A comet is like a space snowball.",
    "Inside there is ice.",
    "But not only water ice.",
    "There are frozen gases too.",
    "And dust and rocks.",
    "When a comet gets close to the Sun, the ice melts.",
    "Gas shoots out.",
    "A bright tail appears.",
    "Inside there is still a solid core.",
    "Comets are very old pieces of space.",
    "They keep secrets from the beginning of the universe, meow."
  ],
},
{
  id: "dark-space-en-001",
  lang: "en",
  prompt: "Why is space so dark?",
  texts: [
    "Meow! There are many stars in space.",
    "But they are very far from each other.",
    "Light does not fill everything.",
    "It travels for millions of years.",
    "There is no air to spread the light.",
    "So space looks black.",
    "Even in daytime, space is dark.",
    "You only see light near a star.",
    "Between stars there is almost nothing.",
    "That is why space seems dark.",
    "It is not scary — just very, very big, meow."
  ],
},
{
  id: "gravity-en-001",
  lang: "en",
  prompt: "What is gravity?",
  texts: [
    "Meow! Gravity is an invisible force.",
    "It pulls things down.",
    "That is why we stand on Earth.",
    "If we jump, we come back down.",
    "The Earth pulls us.",
    "The Moon pulls the oceans.",
    "The Sun keeps planets close.",
    "The bigger something is, the stronger its pull.",
    "We cannot see gravity.",
    "But we feel it every day.",
    "This invisible force keeps the world together, meow."
  ],
},
{
  id: "earth-round-en-001",
  lang: "en",
  prompt: "Why is the Earth round?",
  texts: [
    "Meow! The Earth is round because of gravity.",
    "When our planet was forming, it was hot and soft.",
    "Gravity pulled everything toward the center.",
    "From every side equally.",
    "The easiest shape under that pull is a ball.",
    "Like a drop of water in space.",
    "Big objects become round.",
    "Small rocks can have any shape.",
    "But large planets are almost always round.",
    "That is why Earth looks like a giant ball.",
    "Gravity shaped our home into a sphere, meow."
  ],
},
{
  id: "ice-floats-en-001",
  lang: "en",
  prompt: "Why does ice float?",
  texts: [
    "Meow! Ice floats because it is lighter than water.",
    "When water freezes, it expands.",
    "Its molecules spread a little farther apart.",
    "There is more empty space inside.",
    "That makes ice less dense.",
    "Less dense things float.",
    "That is why ice cubes stay on top.",
    "If ice sank, lakes would freeze from the bottom.",
    "Fish would not survive the winter.",
    "So floating ice helps life.",
    "Smart ice, meow."
  ],
},
{
  id: "electricity-en-001",
  lang: "en",
  prompt: "How does electricity work?",
  texts: [
    "Meow! Electricity is the movement of tiny particles.",
    "These particles are called electrons.",
    "They run through wires.",
    "Like cats running down a hallway.",
    "When electrons move, we get electric current.",
    "That current can light a lamp.",
    "Or power your TV.",
    "To make electrons move, we need a battery or an outlet.",
    "They give the push.",
    "The stronger the movement, the more energy.",
    "That is how electricity powers our world, meow."
  ],
},
{
  id: "lightning-en-001",
  lang: "en",
  prompt: "Why does lightning flash?",
  texts: [
    "Meow! Lightning is a giant spark in the sky.",
    "Electricity builds up inside clouds.",
    "There are positive and negative charges.",
    "When the difference gets too big,",
    "a sudden discharge happens.",
    "It is very fast and very bright.",
    "The air heats up instantly.",
    "That is why we see a flash.",
    "Then we hear thunder.",
    "Light travels faster than sound.",
    "That is why lightning flashes before it booms, meow."
  ],
},
{
  id: "sound-en-001",
  lang: "en",
  prompt: "What is sound?",
  texts: [
    "Meow! Sound is an invisible wave.",
    "When something vibrates, the air starts moving.",
    "These vibrations travel forward.",
    "Like ripples on water.",
    "Our ears catch these waves.",
    "Inside the ear there is a tiny drum.",
    "It starts vibrating too.",
    "The brain turns that into sound.",
    "That is how we hear music and voices.",
    "Even a cat’s purr is vibration.",
    "That is what sound is, meow."
  ],
},
{
  id: "boiling-water-en-001",
  lang: "en",
  prompt: "Why does water boil?",
  texts: [
    "Meow! Water boils when it gets very hot.",
    "Inside water are tiny particles.",
    "When they get hot, they move faster.",
    "Faster and faster.",
    "They start breaking away.",
    "Bubbles appear.",
    "That is steam trying to escape.",
    "When many bubbles rise, water boils.",
    "Boiling means turning into steam.",
    "At one hundred degrees, water changes.",
    "That is why the pot starts bubbling, meow."
  ],
},
{
  id: "rainbow-en-001",
  lang: "en",
  prompt: "Why is the rainbow colorful?",
  texts: [
    "Meow! A rainbow appears after rain.",
    "Tiny water drops float in the air.",
    "Sunlight enters a drop.",
    "Inside, the light splits.",
    "White light has many colors.",
    "Red, orange, yellow and more.",
    "The drop works like a tiny prism.",
    "It spreads the colors apart.",
    "We see a colorful arc in the sky.",
    "Each color bends differently.",
    "That is why the rainbow shines bright, meow."
  ],
},
{
  id: "magnet-en-001",
  lang: "en",
  prompt: "How does a magnet work?",
  texts: [
    "Meow! A magnet pulls certain objects.",
    "It uses an invisible force.",
    "This force is called a magnetic field.",
    "The field surrounds the magnet.",
    "Metal feels this field.",
    "And moves toward the magnet.",
    "Not all things stick.",
    "Wood and plastic do not react.",
    "A magnet has two ends.",
    "They are called poles.",
    "Magnets can pull and even push away, meow."
  ],
},
{
  id: "fire-en-001",
  lang: "en",
  prompt: "Why is fire hot?",
  texts: [
    "Meow! Fire is hot because a fast reaction happens.",
    "When something burns, tiny particles change.",
    "During this change, energy is released.",
    "This energy comes out as heat.",
    "The particles move very fast.",
    "The faster they move, the hotter it feels.",
    "We feel that as warmth or heat.",
    "That is why fire can burn.",
    "Fire gives both light and heat.",
    "Fire is energy turning into heat and light, meow."
  ],
},
{
  id: "atom-en-001",
  lang: "en",
  prompt: "What is an atom?",
  texts: [
    "Meow! An atom is a tiny building block.",
    "Everything is made of atoms.",
    "Even you and me.",
    "Atoms are too small to see.",
    "Inside an atom there is a center.",
    "It is called the nucleus.",
    "Around it move even smaller particles.",
    "They are called electrons.",
    "Atoms join together to make materials.",
    "That is how the world is built.",
    "That is what an atom is, meow."
  ],
},
{
  id: "soap-en-001",
  lang: "en",
  prompt: "Why does soap wash away dirt?",
  texts: [
    "Meow! Soap is a clever helper.",
    "Dirt often contains grease.",
    "Grease does not like water.",
    "Soap molecules have two sides.",
    "One side likes water.",
    "The other side likes grease.",
    "Soap grabs the dirt.",
    "Then water carries it away.",
    "The dirt leaves with the foam.",
    "That is why hands become clean, meow."
  ],
},
{
  id: "leaves-en-001",
  lang: "en",
  prompt: "Why are leaves green?",
  texts: [
    "Meow! Leaves are green because of a special substance.",
    "It is called chlorophyll.",
    "Chlorophyll helps plants get energy.",
    "It catches sunlight.",
    "Sunlight has many colors.",
    "Chlorophyll absorbs most of them.",
    "But it reflects green light.",
    "That is why we see green leaves.",
    "Without chlorophyll plants could not live.",
    "Green is the color of life, meow."
  ],
},
{
  id: "snail-shell-en-001",
  lang: "en",
  prompt: "Why does a snail have a shell?",
  texts: [
    "Meow! A shell is the snail’s house.",
    "It carries it everywhere.",
    "When it feels scared, it hides inside.",
    "The shell protects it from enemies.",
    "It also protects from hot sun.",
    "And from dry air.",
    "Inside the shell it feels safe.",
    "The shell is hard and strong.",
    "It grows as the snail grows.",
    "Without it, survival would be hard.",
    "That is why the snail wears its home, meow."
  ],
},
{
  id: "bees-buzz-en-001",
  lang: "en",
  prompt: "Why do bees buzz?",
  texts: [
    "Meow! Bees buzz because of their wings.",
    "They flap them very fast.",
    "So fast that the air vibrates.",
    "We hear that as buzzing.",
    "Bees flap hundreds of times per second.",
    "That helps them fly.",
    "And carry nectar.",
    "Sometimes buzzing warns others.",
    "It is their working sound.",
    "Like a tiny airplane engine.",
    "That is why flowers hum, meow."
  ],
},
{
  id: "turtle-shell-en-001",
  lang: "en",
  prompt: "How does a turtle hide in its shell?",
  texts: [
    "Meow! The shell is part of the turtle’s body.",
    "It cannot take it off.",
    "There is space inside.",
    "When danger comes, it pulls in its head.",
    "And its legs too.",
    "Strong muscles help it do this.",
    "It folds itself inside.",
    "The shell is hard and strong.",
    "It protects from bites.",
    "The turtle becomes like a rock.",
    "That is how it hides, meow."
  ],
},
{
  id: "fish-float-en-001",
  lang: "en",
  prompt: "Why don’t fish sink?",
  texts: [
    "Meow! Fish have a special air sac inside.",
    "It is called a swim bladder.",
    "It holds air.",
    "Air helps them float.",
    "More air makes them rise.",
    "Less air makes them sink.",
    "They control their depth.",
    "Water supports their bodies.",
    "Fish are close to the weight of water.",
    "That helps them stay balanced.",
    "That is why they do not sink, meow."
  ],
},
{
  id: "whale-breath-en-001",
  lang: "en",
  prompt: "How does a whale breathe?",
  texts: [
    "Meow! A whale lives in water but breathes air.",
    "It is not a fish.",
    "It is a mammal.",
    "Whales have lungs like we do.",
    "They swim up to the surface.",
    "Then they take a big breath.",
    "Air goes through a hole on top of the head.",
    "It is called a blowhole.",
    "When a whale exhales, you see a splash.",
    "Then it dives again.",
    "That is how a whale breathes, meow."
  ],
},
{
  id: "giraffe-neck-en-001",
  lang: "en",
  prompt: "Why does a giraffe have a long neck?",
  texts: [
    "Meow! A giraffe has a long neck to reach leaves.",
    "It eats from very tall trees.",
    "There is less competition up there.",
    "A long neck also helps it see far.",
    "It can spot danger early.",
    "That helps it survive.",
    "A giraffe has the same number of neck bones as we do.",
    "They are just much longer.",
    "Over time nature shaped it this way.",
    "Now it is the tallest animal.",
    "That is why its neck is so long, meow."
  ],
},
{
  id: "ant-day-en-001",
  lang: "en",
  prompt: "What does an ant do all day?",
  texts: [
    "Meow! An ant is almost always busy.",
    "It searches for food.",
    "Then it carries it home.",
    "Home is called an anthill.",
    "Many ants live there.",
    "They build tunnels.",
    "And take care of baby ants.",
    "Each ant has a job.",
    "Some guard the entrance.",
    "Some care for the queen.",
    "An anthill is like a tiny city, meow."
  ],
},
{
  id: "cats-water-en-001",
  lang: "en",
  prompt: "Why are cats afraid of water?",
  texts: [
    "Meow! Not all cats fear water.",
    "But many do not like it.",
    "Wet fur becomes heavy.",
    "And cold.",
    "It takes time to dry.",
    "Cats feel uncomfortable.",
    "In nature cats did not swim much.",
    "They did not need to dive.",
    "So water feels unusual.",
    "Some cats even enjoy baths.",
    "It depends on the cat, meow."
  ],
},
{
  id: "brain-en-001",
  lang: "en",
  prompt: "How does the brain work?",
  texts: [
    "Meow! The brain is the body’s boss.",
    "It controls movement.",
    "It helps us think and remember.",
    "Inside the brain are billions of cells.",
    "They are called neurons.",
    "Neurons send signals.",
    "Like tiny electric sparks.",
    "The signals travel very fast.",
    "That is how we feel and see.",
    "The brain even works while we sleep.",
    "That is our amazing commander, meow."
  ],
},
{
  id: "phone-en-001",
  lang: "en",
  prompt: "How does a phone work?",
  texts: [
    "Meow! A phone sends your voice far away.",
    "When you speak, the microphone catches sound.",
    "It turns sound into an electric signal.",
    "The signal travels through a network.",
    "Or through radio waves.",
    "Another phone receives the signal.",
    "It turns it back into sound.",
    "So someone hears your voice.",
    "All this happens very fast.",
    "Almost instantly.",
    "That is how we talk from far away, meow."
  ],
},
{
  id: "plane-fly-en-001",
  lang: "en",
  prompt: "Why does an airplane fly?",
  texts: [
    "Meow! An airplane flies because of its wings.",
    "The wings have a special shape.",
    "Air moves faster above the wing.",
    "And slower below it.",
    "This creates lifting force.",
    "The lift pushes the plane up.",
    "Engines push it forward.",
    "The faster it moves, the stronger the lift.",
    "The plane balances in the air.",
    "And can travel very far.",
    "That is why it does not fall, meow."
  ],
},
{
  id: "internet-en-001",
  lang: "en",
  prompt: "What is the internet?",
  texts: [
    "Meow! The internet is a huge network.",
    "It connects computers around the world.",
    "Computers share information.",
    "Information can be messages and videos.",
    "Data travels through cables.",
    "And through wireless signals.",
    "Everything is split into tiny pieces.",
    "The pieces travel very fast.",
    "Then they join again at the end.",
    "That is how we talk and learn online.",
    "The internet is a giant connection web, meow."
  ],
},
{
  id: "rocket-en-001",
  lang: "en",
  prompt: "How does a rocket work?",
  texts: [
    "Meow! A rocket is a powerful flying machine.",
    "Inside it there is fuel.",
    "When fuel burns, hot gas forms.",
    "The gas shoots downward.",
    "And the rocket moves upward.",
    "This is called thrust.",
    "A rocket has engines.",
    "It has fuel tanks.",
    "It has a control system.",
    "The system keeps it on course.",
    "That is how a rocket flies into space, meow."
  ],
},
{
  id: "computer-think-en-001",
  lang: "en",
  prompt: "Why can a computer think?",
  texts: [
    "Meow! A computer does not think like a human.",
    "It follows instructions.",
    "Inside it there is a processor.",
    "It processes information.",
    "Everything runs on electric signals.",
    "Signals switch on and off.",
    "This creates code of zeros and ones.",
    "Programs tell the computer what to do.",
    "It calculates very fast.",
    "So it seems like thinking.",
    "But it is just following rules, meow."
  ],
},
{
  id: "battery-en-001",
  lang: "en",
  prompt: "How does a battery work?",
  texts: [
    "Meow! A battery stores energy.",
    "Inside it are special chemicals.",
    "When they react, electricity appears.",
    "Electricity is moving charge.",
    "The charge flows through wires.",
    "It powers devices.",
    "As long as chemicals react, energy flows.",
    "When they are used up, it stops.",
    "That is when the battery is empty.",
    "A battery is a tiny power source, meow."
  ],
},
{
  id: "clock-inside-en-001",
  lang: "en",
  prompt: "What is inside a clock?",
  texts: [
    "Meow! Inside a clock there is a mechanism.",
    "In old clocks there are gears.",
    "They turn very precisely.",
    "And move the hands.",
    "In digital clocks there is a battery.",
    "And a tiny circuit board.",
    "A quartz crystal vibrates evenly.",
    "This keeps time steady.",
    "Clocks count seconds.",
    "Then minutes and hours.",
    "That is how time moves forward, meow."
  ],
},
{
  id: "robot-vacuum-en-001",
  lang: "en",
  prompt: "How does a robot vacuum work?",
  texts: [
    "Meow! A robot vacuum is a tiny cleaner.",
    "Inside it there is a motor.",
    "The motor spins brushes.",
    "The brushes lift dust.",
    "The dust gets sucked inside.",
    "There is a dirt container.",
    "The robot has sensors.",
    "They stop it from hitting walls.",
    "It moves around by itself.",
    "When the battery is low, it returns home.",
    "That is how the little robot cleans, meow."
  ],
},
{
  id: "satellite-en-001",
  lang: "en",
  prompt: "Why do we need satellites?",
  texts: [
    "Meow! A satellite is a machine in space.",
    "It circles around Earth.",
    "Satellites send signals.",
    "They help the internet work.",
    "And television too.",
    "They help navigation.",
    "GPS works through satellites.",
    "Satellites take photos of Earth.",
    "They study weather.",
    "They help scientists watch our planet.",
    "That is why satellites fly above us, meow."
  ],
},
{
  id: "traffic-light-en-001",
  lang: "en",
  prompt: "How does a traffic light work?",
  texts: [
    "Meow! A traffic light controls traffic.",
    "It has three colors.",
    "Red means stop.",
    "Yellow means get ready.",
    "Green means go.",
    "Inside there is a timer.",
    "It counts time.",
    "The lights change in order.",
    "Some lights react to cars.",
    "They help prevent crashes.",
    "That is how roads stay safe, meow."
  ],
},
{
  id: "two-plus-two-en-001",
  lang: "en",
  prompt: "Why is 2 + 2 equal to 4?",
  texts: [
    "Meow! Two means two objects.",
    "If you add two more, you have more.",
    "Imagine two toys.",
    "And two more toys.",
    "Let’s count: one, two, three, four.",
    "Now there are four toys.",
    "This rule always works.",
    "That is how math is built.",
    "Numbers help us count correctly.",
    "So two plus two is always four.",
    "Math loves order, meow."
  ],
},
{
  id: "infinity-en-001",
  lang: "en",
  prompt: "What is infinity?",
  texts: [
    "Meow! Infinity means no ending.",
    "Imagine a very long road.",
    "You walk and walk.",
    "But it never stops.",
    "Numbers can go on forever too.",
    "After a million, there is more.",
    "And even more.",
    "You cannot finish counting infinity.",
    "You cannot put it in a box.",
    "But you can imagine it.",
    "That huge idea is infinity, meow."
  ],
},
{
  id: "numbers-en-001",
  lang: "en",
  prompt: "Why do we need numbers?",
  texts: [
    "Meow! Numbers help us count.",
    "How many apples are there?",
    "How many steps to school?",
    "Without numbers, everything is confusing.",
    "Numbers help us compare.",
    "What is bigger and what is smaller.",
    "We use them in shops.",
    "And in games.",
    "And in science.",
    "Numbers make the world clearer.",
    "That is why we need them, meow."
  ],
},
{
  id: "divide-zero-en-001",
  lang: "en",
  prompt: "Why can't we divide by zero?",
  texts: [
    "Meow! Dividing means sharing.",
    "If you have four cookies and two friends.",
    "Each gets two.",
    "But what if there are zero friends?",
    "There is nobody to share with.",
    "You cannot divide by nobody.",
    "It makes math confused.",
    "Math does not like that.",
    "So we do not divide by zero.",
    "It is like sharing air.",
    "It just does not work, meow."
  ],
},
{
  id: "count-faster-en-001",
  lang: "en",
  prompt: "How can I count faster?",
  texts: [
    "Meow! Practice makes counting faster.",
    "Train a little every day.",
    "Learn the multiplication table.",
    "Group things in twos or fives.",
    "Look for patterns.",
    "Break big numbers into smaller ones.",
    "Use your fingers if needed.",
    "Play math games.",
    "Do not rush too much.",
    "Be correct first, then fast.",
    "Soon counting will feel easy, meow."
  ],
},
{
  id: "probability-en-001",
  lang: "en",
  prompt: "What is probability?",
  texts: [
    "Meow! Probability means chance.",
    "Like the chance it will rain.",
    "Or the chance to roll a six.",
    "Sometimes the chance is big.",
    "Sometimes it is small.",
    "Flip a coin.",
    "Heads and tails are almost equal.",
    "That means the chances are similar.",
    "Probability helps us guess.",
    "It does not give a sure answer.",
    "But it shows what is more likely, meow."
  ],
},
{
  id: "circle-en-001",
  lang: "en",
  prompt: "Why is a circle round?",
  texts: [
    "Meow! A circle is round because it has no corners.",
    "Every point is the same distance from the center.",
    "Imagine a dot in the middle.",
    "Tie a string to it.",
    "Pull the string tight.",
    "Move it around.",
    "You draw a circle.",
    "It has no sharp edges.",
    "It is smooth all around.",
    "That is its special shape.",
    "That is why a circle is round, meow."
  ],
},
{
  id: "geometry-en-001",
  lang: "en",
  prompt: "How was geometry invented?",
  texts: [
    "Meow! Geometry started when people needed to build.",
    "They had to measure land.",
    "Build houses.",
    "And divide fields.",
    "They noticed shapes.",
    "Triangles, circles and lines.",
    "They studied them.",
    "Tested rules.",
    "Wrote them down.",
    "That became the science of shapes.",
    "That is how geometry was born, meow."
  ],
},
{
  id: "fractions-en-001",
  lang: "en",
  prompt: "Why do we need fractions?",
  texts: [
    "Meow! Fractions help when things are not whole.",
    "One pizza.",
    "Four friends.",
    "Each gets a part.",
    "That is one fourth.",
    "Fractions show pieces.",
    "Not the whole thing.",
    "They help us share fairly.",
    "And count more exactly.",
    "We use them in cooking.",
    "That is why fractions matter, meow."
  ],
},
{
  id: "cipher-en-001",
  lang: "en",
  prompt: "How does a cipher work?",
  texts: [
    "Meow! A cipher is a secret way to write.",
    "It turns normal words into secret symbols.",
    "For example, A can become D.",
    "Then no one understands it right away.",
    "Only the person who knows the rule.",
    "That rule is called a key.",
    "With the key, you can decode it.",
    "Without it, the text looks strange.",
    "Ciphers help keep secrets.",
    "And protect important messages.",
    "That is how a cipher works, meow."
  ],
},
{
  id: "seasons-en-001",
  lang: "en",
  prompt: "Why do seasons change?",
  texts: [
    "Meow! Seasons change because Earth moves.",
    "Earth goes around the Sun.",
    "And it is slightly tilted.",
    "Sometimes one side faces the Sun more.",
    "That side has summer.",
    "The other side gets less light.",
    "That is winter.",
    "Later they switch places.",
    "That brings spring and autumn.",
    "It is like a space dance.",
    "That is why seasons change, meow."
  ],
},
{
  id: "mountains-en-001",
  lang: "en",
  prompt: "How do mountains form?",
  texts: [
    "Meow! Mountains grow very slowly.",
    "Earth is made of huge plates.",
    "They move.",
    "Sometimes they crash into each other.",
    "The ground pushes up.",
    "And mountains rise.",
    "Some mountains come from volcanoes.",
    "Wind and water shape them too.",
    "Mountains can be very old.",
    "They grow over millions of years.",
    "That is how mountains form, meow."
  ],
},
{
  id: "volcano-en-001",
  lang: "en",
  prompt: "What is a volcano?",
  texts: [
    "Meow! A volcano is an opening in the Earth.",
    "Deep inside, it is very hot.",
    "There is melted rock.",
    "It is called lava.",
    "Sometimes lava rises up.",
    "And bursts out.",
    "That is an eruption.",
    "Smoke and ash can come out too.",
    "When lava cools, it becomes rock.",
    "New land can form.",
    "That is what a volcano is, meow."
  ],
},
{
  id: "oceans-en-001",
  lang: "en",
  prompt: "Why do we need oceans?",
  texts: [
    "Meow! Oceans are huge water bowls of Earth.",
    "They hold most of the planet’s water.",
    "They help Earth not get too hot.",
    "Ocean water moves around.",
    "It carries heat across the planet.",
    "Many creatures live there.",
    "Fish, whales and tiny life forms.",
    "Oceans help us breathe.",
    "Small plants in water make oxygen.",
    "They also shape the weather.",
    "That is why we need oceans, meow."
  ],
},
{
  id: "earthquake-en-001",
  lang: "en",
  prompt: "Why do earthquakes happen?",
  texts: [
    "Meow! Earth is not completely still.",
    "It is made of huge plates.",
    "These plates move slowly.",
    "Sometimes they get stuck.",
    "Then they suddenly slip.",
    "The ground shakes.",
    "That is an earthquake.",
    "Some shakes are small.",
    "Some are strong.",
    "It happens deep underground.",
    "That is why earthquakes happen, meow."
  ],
},
{
  id: "clouds-en-001",
  lang: "en",
  prompt: "Where do clouds come from?",
  texts: [
    "Meow! Clouds come from water.",
    "Water warms up and turns into vapor.",
    "Vapor rises into the sky.",
    "Up high it is cold.",
    "Vapor turns into tiny drops.",
    "The drops gather together.",
    "That makes a cloud.",
    "Some clouds are light and fluffy.",
    "Some are dark and heavy.",
    "It all starts with water.",
    "That is where clouds come from, meow."
  ],
},
{
  id: "rain-en-001",
  lang: "en",
  prompt: "Why does it rain?",
  texts: [
    "Meow! Rain begins in clouds.",
    "Clouds hold tiny water drops.",
    "The drops bump into each other.",
    "They grow bigger.",
    "When a drop gets heavy.",
    "It falls down.",
    "That is rain.",
    "Sometimes rain is gentle.",
    "Sometimes it pours.",
    "Rain helps plants grow.",
    "That is why it rains, meow."
  ],
},
{
  id: "swimming-en-001",
  lang: "en",
  prompt: "How did people learn to swim?",
  texts: [
    "Meow! People did not always know how to swim.",
    "At first they were afraid of water.",
    "But rivers and seas were everywhere.",
    "People watched animals.",
    "They saw dogs and cats moving their legs.",
    "Then they tried it themselves.",
    "They moved arms and legs.",
    "Sometimes it looked funny.",
    "Sometimes it felt scary.",
    "Slowly their bodies learned to float.",
    "That is how people learned to swim, meow."
  ],
},
{
  id: "languages-en-001",
  lang: "en",
  prompt: "Why do people have different languages?",
  texts: [
    "Meow! Long ago people lived far apart.",
    "They did not meet often.",
    "Each group made their own words.",
    "The words sounded different.",
    "Over time new languages appeared.",
    "Language helps people understand each other.",
    "It keeps history and traditions.",
    "Some languages are similar.",
    "Some are very different.",
    "All of them help people talk.",
    "That is why we have different languages, meow."
  ],
},
{
  id: "holidays-en-001",
  lang: "en",
  prompt: "Why do we need holidays?",
  texts: [
    "Meow! Holidays make life brighter.",
    "On normal days we are busy.",
    "A holiday is a pause.",
    "It is time for joy and meeting others.",
    "People remember important events.",
    "They give gifts and kind words.",
    "Holidays bring families together.",
    "They help us feel part of something bigger.",
    "Even cats like special days.",
    "Holidays remind us to celebrate.",
    "That is why we need holidays, meow."
  ],
},
{
  id: "drawing-en-001",
  lang: "en",
  prompt: "Why do people draw?",
  texts: [
    "Meow! People draw to show their thoughts.",
    "Sometimes words are not enough.",
    "A picture can explain everything.",
    "Drawing shares feelings.",
    "It helps people dream.",
    "You can draw things that do not exist yet.",
    "Drawings keep memories.",
    "They can be funny or serious.",
    "Each drawing tells a small story.",
    "Even a cat can be an artist.",
    "That is why people draw, meow."
  ],
},
{
  id: "music-emotions-en-001",
  lang: "en",
  prompt: "Why does music create emotions?",
  texts: [
    "Meow! Music is sound with feelings.",
    "Sounds can be fast or slow.",
    "Loud or soft.",
    "Our brain listens and compares.",
    "It remembers similar moments.",
    "Soft melodies feel calm.",
    "Fast rhythms make us move.",
    "Music touches memory.",
    "And it touches the heart.",
    "That is why we may laugh or cry.",
    "That is why music creates emotions, meow."
  ],
},
{
  id: "portrait-en-001",
  lang: "en",
  prompt: "How does an artist draw portraits?",
  texts: [
    "Meow! A portrait is a picture of a person.",
    "The artist first looks carefully.",
    "They notice the shape of the face.",
    "They see the eyes and smile.",
    "Then they make a light sketch.",
    "They add details.",
    "They choose the right colors.",
    "They try to show the mood.",
    "Not only the face but the character.",
    "Every line matters.",
    "That is how an artist draws a portrait, meow."
  ],
},
{
  id: "fairytales-en-001",
  lang: "en",
  prompt: "How are fairy tales created?",
  texts: [
    "Meow! A fairy tale starts with an idea.",
    "Sometimes with a question.",
    "Or with a hero.",
    "Then an adventure begins.",
    "The hero faces a problem.",
    "A helper appears.",
    "Or some magic.",
    "The story moves toward a solution.",
    "At the end the hero changes.",
    "A fairy tale teaches something important.",
    "That is how fairy tales are made, meow."
  ],
},
{
  id: "dance-en-001",
  lang: "en",
  prompt: "Why do people dance?",
  texts: [
    "Meow! Dance is movement with feeling.",
    "When music plays, the body wants to move.",
    "Sometimes people dance from joy.",
    "Sometimes from excitement.",
    "Dance helps express emotions.",
    "You can dance alone.",
    "Or together.",
    "Dance brings people closer.",
    "It makes the mood brighter.",
    "Even a cat might jump to music.",
    "That is why people dance, meow."
  ],
},
{
  id: "theater-en-001",
  lang: "en",
  prompt: "What is theater?",
  texts: [
    "Meow! Theater is a place where stories come alive.",
    "Actors stand on a stage.",
    "They pretend to be other people.",
    "They talk, move and perform.",
    "The audience watches and listens.",
    "Sometimes it is funny.",
    "Sometimes it is sad.",
    "Lights and music create the mood.",
    "Every show is a little different.",
    "Because it happens right now.",
    "That is what theater is, meow."
  ],
},
{
  id: "expensive-painting-en-001",
  lang: "en",
  prompt: "Why can a painting be expensive?",
  texts: [
    "Meow! A painting is more than colors.",
    "Sometimes a famous artist made it.",
    "There are only a few like it.",
    "People value rare things.",
    "A painting can be very old.",
    "It can hold a piece of history.",
    "Sometimes it has a special idea.",
    "Or a unique style.",
    "People are willing to pay for art.",
    "Price shows how much people value it.",
    "That is why a painting can be expensive, meow."
  ],
},
{
  id: "poems-en-001",
  lang: "en",
  prompt: "Why do we memorize poems?",
  texts: [
    "Meow! Poems are words with rhythm.",
    "When we memorize them, memory gets stronger.",
    "We learn to hear language better.",
    "Poems help us speak clearly.",
    "And feel the meaning of words.",
    "Some lines stay with us for years.",
    "They can comfort us.",
    "Poems teach us to notice beauty.",
    "And think deeper.",
    "It is like exercise for the brain.",
    "That is why we memorize poems, meow."
  ],
},
{
  id: "cartoon-en-001",
  lang: "en",
  prompt: "How is a cartoon made?",
  texts: [
    "Meow! A cartoon is many pictures in a row.",
    "Each picture is a little different.",
    "When they move fast.",
    "It looks like motion.",
    "Artists draw the characters.",
    "Animators move them step by step.",
    "They add voices and music.",
    "Sometimes they use computers.",
    "Sometimes they draw by hand.",
    "It takes a whole team.",
    "That is how a cartoon works, meow."
  ],
},
{
  id: "reading-en-001",
  lang: "en",
  prompt: "Why is it important to read books?",
  texts: [
    "Meow! Books are doors to other worlds.",
    "When you read, your brain starts working.",
    "It creates pictures inside.",
    "It learns new words.",
    "It understands other people’s thoughts.",
    "Books help you focus better.",
    "And think deeper.",
    "You can travel through stories.",
    "Without leaving home.",
    "Every book makes you a little smarter.",
    "That is why reading books is important, meow."
  ],
},
{
  id: "zebra-en-001",
  lang: "en",
  prompt: "Why is a zebra striped?",
  texts: [
    "Meow! Zebra stripes are not random.",
    "They help zebras hide.",
    "When many zebras stand together.",
    "Predators get confused.",
    "The stripes mix together.",
    "They also help against insects.",
    "Some flies avoid striped patterns.",
    "Each zebra has a unique pattern.",
    "Like a fingerprint.",
    "Stripes are protection.",
    "That is why zebras are striped, meow."
  ],
},
{
  id: "bubble-en-001",
  lang: "en",
  prompt: "How does a bubble work?",
  texts: [
    "Meow! A bubble is air inside a thin film.",
    "The film is made of soap and water.",
    "There is air inside.",
    "And air outside.",
    "The film stretches into a round shape.",
    "Round is the easiest shape to hold.",
    "It stays as long as the film is strong.",
    "If the film breaks.",
    "The bubble pops.",
    "It disappears in a second.",
    "That is how a bubble works, meow."
  ],
},
{
  id: "tickle-en-001",
  lang: "en",
  prompt: "Why are we afraid of tickling?",
  texts: [
    "Meow! Tickling is an unexpected touch.",
    "Our body does not like surprises.",
    "The brain thinks something strange is happening.",
    "It reacts very fast.",
    "We laugh.",
    "But the laugh is a defense.",
    "Tickling feels like a tiny warning.",
    "When we tickle ourselves.",
    "We do not feel scared.",
    "Because the brain already knows.",
    "That is why tickling makes us react, meow."
  ],
},
{
  id: "cactus-en-001",
  lang: "en",
  prompt: "What does a cactus do in the desert?",
  texts: [
    "Meow! A cactus survives in the desert.",
    "The desert is hot and dry.",
    "A cactus stores water inside.",
    "Its thick stem is like a bottle.",
    "It has no regular leaves.",
    "Instead it has spines.",
    "The spines protect it.",
    "They also help save water.",
    "Its roots quickly catch rain.",
    "A cactus is patient and strong.",
    "That is what a cactus does in the desert, meow."
  ],
},
{
  id: "crocodile-en-001",
  lang: "en",
  prompt: "Why does a crocodile have teeth outside?",
  texts: [
    "Meow! A crocodile’s teeth are always visible.",
    "Its jaws do not fully hide them.",
    "The teeth are long and sharp.",
    "They help catch prey.",
    "A crocodile does not chew like us.",
    "It grabs and swallows.",
    "The teeth hold food tightly.",
    "If a tooth breaks.",
    "A new one grows.",
    "That helps with hunting.",
    "That is why crocodiles have teeth outside, meow."
  ],
},
{
  id: "butterfly-en-001",
  lang: "en",
  prompt: "How do butterflies fly?",
  texts: [
    "Meow! A butterfly flies with its wings.",
    "It has four light wings.",
    "The wings have tiny scales.",
    "It moves them up and down.",
    "Air lifts the butterfly.",
    "The wings work like small sails.",
    "Butterflies are very light.",
    "So they stay in the air easily.",
    "They can glide softly.",
    "Or quickly escape.",
    "That is how butterflies fly, meow."
  ],
},
{
  id: "snail-en-001",
  lang: "en",
  prompt: "Why is a snail slow?",
  texts: [
    "Meow! A snail moves in a special way.",
    "It has no legs.",
    "It crawls on its soft body.",
    "Its body moves slowly.",
    "It leaves slime behind.",
    "The slime helps it slide.",
    "But it is still slow.",
    "A snail never rushes.",
    "Its shell is heavy.",
    "It lives calmly.",
    "That is why a snail is slow, meow."
  ],
},
{
  id: "mirage-en-001",
  lang: "en",
  prompt: "What is a mirage?",
  texts: [
    "Meow! A mirage is a trick of the eyes.",
    "It appears in hot air.",
    "Hot and cold air mix together.",
    "Light bends.",
    "Our eyes see something that is not there.",
    "Like water in the desert.",
    "But it is only the sky reflecting.",
    "The brain thinks it is a lake.",
    "But it is just sand.",
    "It is a game of light and air.",
    "That is what a mirage is, meow."
  ],
},
{
  id: "laser-cats-en-001",
  lang: "en",
  prompt: "Why do cats chase lasers?",
  texts: [
    "Meow! Cats love to hunt.",
    "A laser dot looks like prey.",
    "It moves very fast.",
    "The cat wants to catch it.",
    "It wakes up hunting instincts.",
    "The cat jumps and runs.",
    "It trains its body.",
    "But the dot cannot be caught.",
    "So give a real toy sometimes.",
    "So the cat can feel victory.",
    "That is why cats chase lasers, meow."
  ],
},
{
  id: "whales-en-001",
  lang: "en",
  prompt: "Why do whales sing?",
  texts: [
    "Meow! Whales sing underwater.",
    "Their songs are very long.",
    "Sound travels well in water.",
    "This is how whales talk.",
    "They call each other.",
    "Or look for a partner.",
    "Each group sings differently.",
    "Songs can change over time.",
    "It is a way to send messages.",
    "And show strength.",
    "That is why whales sing, meow."
  ],
},
{
  id: "be-yourself-en-001",
  lang: "en",
  prompt: "Why is it important to be yourself?",
  texts: [
    "Meow! Every cat is special.",
    "And every person too.",
    "If you pretend to be someone else.",
    "It feels heavy.",
    "Being yourself means being honest.",
    "It helps you find real friends.",
    "Friends who like the real you.",
    "You can make mistakes.",
    "You can grow and change.",
    "But remember who you are.",
    "That is why it is important to be yourself, meow."
  ],
},
{
  id: "understand-person-en-001",
  lang: "en",
  prompt: "How can you understand another person?",
  texts: [
    "Meow! Understanding someone is like listening to a soft purr.",
    "Everyone has feelings inside.",
    "Sometimes they are hidden.",
    "You need to listen carefully.",
    "And look with more than just your eyes.",
    "Words are only part of the story.",
    "Body language and mood matter too.",
    "You can ask gently.",
    "Do not interrupt.",
    "When you truly try, people feel it.",
    "That is how we learn to understand each other, meow."
  ],
},
{
  id: "empathy-en-001",
  lang: "en",
  prompt: "What is empathy?",
  texts: [
    "Meow! Empathy is feeling someone else's mood.",
    "It is like one heart hearing another.",
    "If someone is sad, you notice.",
    "And you want to help.",
    "It is not pity.",
    "It is understanding.",
    "You imagine being in their place.",
    "And choose kindness.",
    "Empathy makes the world warmer.",
    "It helps us make friends.",
    "That is what empathy is, meow."
  ],
},
{
  id: "mistakes-en-001",
  lang: "en",
  prompt: "Why do we make mistakes?",
  texts: [
    "Meow! Everyone makes mistakes.",
    "We do not know everything.",
    "Sometimes we hurry.",
    "Sometimes we worry.",
    "Sometimes we try something new.",
    "Mistakes help us learn.",
    "They show what we can improve.",
    "Without mistakes there is no growth.",
    "It is okay to admit them.",
    "And learn from them.",
    "That is why we make mistakes, meow."
  ],
},
{
  id: "brave-en-001",
  lang: "en",
  prompt: "How can you become brave?",
  texts: [
    "Meow! Being brave does not mean no fear.",
    "It means taking a step anyway.",
    "Everyone feels scared sometimes.",
    "Even strong people.",
    "Start with small steps.",
    "Try something a little scary.",
    "Do not shame yourself.",
    "Each time it gets easier.",
    "Bravery grows inside you.",
    "Like a tiny flame.",
    "That is how you become brave, meow."
  ],
},
{
  id: "thank-you-en-001",
  lang: "en",
  prompt: "Why is it important to say “thank you”?",
  texts: [
    "Meow! “Thank you” is a small but warm word.",
    "When you say it, people feel good.",
    "It shows you noticed their kindness.",
    "People like to feel seen.",
    "Thank you makes the world softer.",
    "It is like a gentle pat.",
    "Even a simple thank you can brighten a day.",
    "Gratitude makes your heart lighter.",
    "People help more when they feel appreciated.",
    "Thank you connects people.",
    "That is why it matters, meow."
  ],
},
{
  id: "make-friends-en-001",
  lang: "en",
  prompt: "How can you make friends?",
  texts: [
    "Meow! Friendship starts with a small step.",
    "You can say hello.",
    "And smile.",
    "Ask what they like to play.",
    "Be honest.",
    "Do not pretend.",
    "Listen carefully.",
    "Sometimes it takes time.",
    "Shared interests help.",
    "Kindness is the key.",
    "That is how friends appear, meow."
  ],
},
{
  id: "sharing-en-001",
  lang: "en",
  prompt: "Why should we share?",
  texts: [
    "Meow! Sharing means not keeping everything for yourself.",
    "When you share, joy grows.",
    "Toys are more fun together.",
    "Food tastes better with a friend.",
    "Sharing builds trust.",
    "It shows friendship.",
    "It brings people closer.",
    "Sometimes sharing is hard.",
    "But afterward you feel warmer inside.",
    "Generosity makes you stronger.",
    "That is why sharing matters, meow."
  ],
},
{
  id: "care-en-001",
  lang: "en",
  prompt: "What does it mean to care?",
  texts: [
    "Meow! To care means to notice someone.",
    "It means asking if they are okay.",
    "It means helping when it is hard.",
    "It means staying close when someone is sad.",
    "Care is attention.",
    "And patience.",
    "Sometimes caring means just listening.",
    "Sometimes it means giving a warm blanket.",
    "Caring makes the world softer.",
    "It makes relationships stronger.",
    "That is what caring means, meow."
  ],
},
{
  id: "alone-en-001",
  lang: "en",
  prompt: "Why do we sometimes want to be alone?",
  texts: [
    "Meow! Even cats need quiet sometimes.",
    "Too much noise makes the brain tired.",
    "People get tired of talking too.",
    "Being alone is like charging a battery.",
    "Silence helps you think.",
    "You can notice your feelings.",
    "It does not mean you do not like others.",
    "You just need some space.",
    "After resting, you want to connect again.",
    "Alone time can make you calmer.",
    "That is why we sometimes want to be alone, meow."
  ],
},
{
  id: "forgive-en-001",
  lang: "en",
  prompt: "How can we learn to forgive?",
  texts: [
    "Meow! Forgiving is not easy.",
    "When someone hurts you, it feels heavy.",
    "Holding anger is heavy too.",
    "Forgiveness is like dropping a big stone.",
    "It does not mean forgetting everything.",
    "It means letting go of anger.",
    "You can talk about it first.",
    "Try to understand what happened.",
    "Sometimes it takes time.",
    "Forgiving makes your heart lighter.",
    "That is how we learn to forgive, meow."
  ],
},
{
  id: "listen-en-001",
  lang: "en",
  prompt: "Why is it important to listen to others?",
  texts: [
    "Meow! Listening is more than staying quiet.",
    "When you listen, people feel important.",
    "You can learn something new.",
    "Everyone sees the world differently.",
    "Other words can help you understand yourself.",
    "Listening builds trust.",
    "Without it, fights happen easily.",
    "Listening shows respect.",
    "Real conversations begin there.",
    "Friendships grow stronger.",
    "That is why listening matters, meow."
  ],
},
{
  id: "school-en-001",
  lang: "en",
  prompt: "Why do we go to school?",
  texts: [
    "Meow! School is more than lessons.",
    "You learn to read, count, and think.",
    "Your brain grows stronger.",
    "You discover how the world works.",
    "You can make friends.",
    "You learn to work together.",
    "Sometimes it feels hard.",
    "But hard work helps you grow.",
    "School opens new doors.",
    "It prepares you for adult life.",
    "That is why we go to school, meow."
  ],
},
];