export type MusicSlide = {
  text: string;
  mediaUrl?: string;
};

export type MusicStyle = {
  slug: string;
  title: string;
  description?: string;
  slides: MusicSlide[];
};

export const musicStyles_ru: MusicStyle[] = [
  {
    slug: "lofi",
    title: "Lo-fi chill",
    slides: [
      { text: "Представь: дождь за окном, ты сидишь с ноутбуком, и мир становится чуть тише... это и есть lo-fi." },
      { text: "Lo-fi появился из хип-хопа 90-х, когда музыканты начали делать музыку для спокойного настроения и концентрации." },
      { text: "Название значит 'low fidelity' — звук специально делают немного шероховатым, будто старая кассета." },
      { text: "Главный инструмент — это бит: мягкий, медленный и очень ровный, без резких ударов." },
      { text: "Часто добавляют пианино, гитару или джазовые аккорды, чтобы музыка звучала тепло и уютно." },
      { text: "Фоновые звуки — дождь, треск винила, шум комнаты — делают атмосферу живой." },
      { text: "Lo-fi почти никогда не отвлекает, поэтому его слушают во время учёбы или работы." },
      { text: "Этот стиль стал популярным благодаря стримам с бесконечной музыкой, например 'lofi girl'." },
      { text: "В lo-fi важнее настроение, чем сложность музыки — всё должно звучать просто и спокойно." },
      { text: "Известные исполнители: Nujabes, J Dilla, Idealism." },
      { text: "Lo-fi — это музыка, которая не требует внимания, но делает любое занятие приятнее." },
      { text: "А ты где бы включил lo-fi: во время учёбы, перед сном или просто чтобы почувствовать уют?" },
    ],
  },
  {
    slug: "bossa",
    title: "Bossa-nova",
    slides: [
      { text: "Представь: тёплый вечер, океан, и ты идёшь босиком по песку... звучит bossa nova." },
      { text: "Bossa nova появилась в Бразилии в конце 1950-х годов как мягкая версия самбы." },
      { text: "Музыканты хотели сделать музыку спокойнее и более интимной, для небольших пространств." },
      { text: "Главный инструмент — классическая гитара, которая играет плавный и покачивающий ритм." },
      { text: "Также используются лёгкие барабаны, пианино и мягкий вокал почти шёпотом." },
      { text: "Ритм босса-новы как будто качается, создавая ощущение прогулки у моря." },
      { text: "Этот стиль быстро стал популярным по всему миру благодаря своей лёгкости." },
      { text: "Самая известная песня — 'The Girl from Ipanema'." },
      { text: "Главные исполнители: João Gilberto, Antônio Carlos Jobim, Stan Getz." },
      { text: "Bossa nova часто звучит в кафе, фильмах и спокойных вечерах." },
      { text: "Эта музыка не требует громкости — она работает через настроение и атмосферу." },
      { text: "А ты где бы слушал bossa nova: на отдыхе, дома с чаем или в дороге?" },
    ],
  },
  {
    slug: "synthwave",
    title: "Synthwave",
    slides: [
      { text: "Представь: ночь, неоновый город и ты мчишься по шоссе... это мир synthwave." },
      { text: "Synthwave вдохновлён музыкой и фильмами 1980-х годов, особенно научной фантастикой." },
      { text: "Этот стиль появился позже — как ностальгия по эпохе кассет, аркад и неоновых огней." },
      { text: "Главный инструмент — синтезатор, который создаёт яркие и 'светящиеся' звуки." },
      { text: "Также используются электронные барабаны и мощный ритм, похожий на саундтреки к фильмам." },
      { text: "Музыка часто звучит так, будто ты едешь ночью по шоссе в неоновом городе." },
      { text: "Synthwave почти всегда инструментальный, но иногда добавляют атмосферный вокал." },
      { text: "Стиль стал популярным благодаря играм, фильмам и YouTube-видео с ретро-эстетикой." },
      { text: "Известные исполнители: Kavinsky, The Midnight, Perturbator." },
      { text: "Synthwave часто используют в играх, трейлерах и фоновой музыке для видео." },
      { text: "Это музыка не только про звук, но и про визуальный мир: неон, закаты и ретро-технологии." },
      { text: "А ты бы включил synthwave: в игре, в машине или просто чтобы почувствовать себя героем фильма?" },
    ],
  },
  {
    slug: "funk",
    title: "Funk",
    slides: [
      { text: "Представь: ты идёшь по улице и вдруг ноги сами начинают двигаться… это значит включился funk." },
      { text: "Funk появился в США в 1960-х, когда музыканты сделали ритм главным героем музыки." },
      { text: "Главный инструмент — бас-гитара, которая играет упругие и очень заметные линии." },
      { text: "Гитара в фанке часто не поёт, а как будто щёлкает короткими ритмичными звуками." },
      { text: "Барабаны играют чётко и сухо, чтобы весь трек держался на груве." },
      { text: "Funk — это про грув: музыка как будто пружинит и заставляет тело двигаться." },
      { text: "Этот стиль стал основой для диско, хип-хопа и многих современных жанров." },
      { text: "Известные исполнители: James Brown, Parliament-Funkadelic, Prince." },
      { text: "Funk часто звучит на танцполах, в фильмах и там, где нужна энергия и движение." },
      { text: "Эта музыка не просит — она заставляет двигаться." },
      { text: "А ты бы начал танцевать сразу или сначала сделал бы вид, что держишься?" },
    ],
  },
  {
    slug: "house",
    title: "House",
    slides: [
      { text: "Представь: тёмный клуб, свет мигает, и бит идёт как сердце… это house." },
      { text: "House появился в 1980-х в Чикаго, когда диджеи начали делать музыку для вечеринок." },
      { text: "Главный элемент — ровный бит 'тук-тук-тук-тук', который не останавливается." },
      { text: "Поверх бита добавляют простые мелодии, вокальные кусочки и синтезаторы." },
      { text: "Музыка постепенно меняется, но не резко — чтобы люди не переставали танцевать." },
      { text: "House создаёт ощущение бесконечного движения, как будто трек не закончится." },
      { text: "Этот стиль стал основой клубной культуры по всему миру." },
      { text: "Известные артисты: Frankie Knuckles, Daft Punk, David Guetta." },
      { text: "House чаще всего звучит в клубах, на фестивалях и вечеринках." },
      { text: "Главная задача — держать тебя в ритме как можно дольше." },
      { text: "А ты бы выдержал танцевать под house целый час без остановки?" },
    ],
  },
  {
    slug: "reggae",
    title: "Reggae",
    slides: [
      { text: "Представь: солнце, море и лёгкий ветер… и музыка будто покачивается вместе с тобой — это reggae." },
      { text: "Reggae появился на Ямайке в 1960-х и быстро стал голосом культуры и настроения острова." },
      { text: "Главный ритм в регги необычный: акцент делают не на сильную долю, а на слабую." },
      { text: "Из-за этого музыка как будто качается из стороны в сторону." },
      { text: "Бас в регги глубокий и тёплый, он создаёт основу всего трека." },
      { text: "Гитара играет короткие акценты, а барабаны держат спокойный ритм." },
      { text: "Reggae часто несёт идеи свободы, мира и спокойствия." },
      { text: "Самый известный исполнитель — Bob Marley." },
      { text: "Эта музыка звучит на пляжах, в путешествиях и в моменты отдыха." },
      { text: "Reggae не торопится — он учит замедляться." },
      { text: "А ты бы слушал reggae лёжа на пляже или просто чтобы расслабиться дома?" },
    ],
  },
  {
    slug: "ambient",
    title: "Ambient",
    slides: [
      { text: "Представь: ты в огромном пространстве, где звуки не спешат, а медленно плывут вокруг тебя… это ambient." },
      { text: "Ambient появился в 1970-х, когда музыканты решили делать музыку не для ритма, а для атмосферы." },
      { text: "Здесь почти нет ударных — главное это длинные, тянущиеся звуки." },
      { text: "Часто используют синтезаторы, эффекты эха и записи окружающих звуков." },
      { text: "Музыка как будто создаёт пространство, а не мелодию." },
      { text: "Ambient можно слушать, а можно просто жить внутри него, как в фоне." },
      { text: "Этот стиль часто используют в фильмах, играх и медитациях." },
      { text: "Известные исполнители: Brian Eno, Aphex Twin, Stars of the Lid." },
      { text: "Ambient помогает сосредоточиться или наоборот полностью расслабиться." },
      { text: "Иногда кажется, что музыка вообще не меняется — но именно в этом её магия." },
      { text: "А ты бы включил ambient для сна, работы или просто чтобы 'раствориться' в звуке?" },
    ],
  },
  {
    slug: "jazzhop",
    title: "Jazzhop",
    slides: [
      { text: "Представь: уютное кафе, мягкий свет и кто-то играет джаз… но с современным битом — это jazzhop." },
      { text: "Jazzhop появился как смесь джаза и хип-хопа, соединяя старое и новое." },
      { text: "От джаза он взял живые инструменты и сложные аккорды." },
      { text: "От хип-хопа — спокойный, качающий бит." },
      { text: "Часто звучат пианино, саксофон, контрабас и мягкие барабаны." },
      { text: "Музыка ощущается как прогулка по городу вечером." },
      { text: "Jazzhop идеально подходит для учёбы, чтения или рисования." },
      { text: "Известные исполнители: Nujabes, Jinsang, Tomppabeats." },
      { text: "Этот стиль часто звучит в плейлистах 'chill' и 'study beats'." },
      { text: "Он одновременно расслабляет и держит лёгкий ритм." },
      { text: "А ты бы включил jazzhop дома, в наушниках на улице или во время учёбы?" },
    ],
  },
  {
    slug: "chiptune",
    title: "Chiptune",
    slides: [
      { text: "Представь: ты включаешь старую приставку, и музыка сразу становится пиксельной… это chiptune." },
      { text: "Chiptune появился из музыки старых видеоигр 80–90-х." },
      { text: "Тогда у компьютеров было очень мало мощности, поэтому звуки были простыми." },
      { text: "Используются базовые волны: писк, щелчки и короткие ноты." },
      { text: "Из этих простых звуков создают быстрые и яркие мелодии." },
      { text: "Музыка часто звучит энергично и немного 'игрушечно'." },
      { text: "Chiptune стал отдельным стилем, даже когда технологии уже стали мощнее." },
      { text: "Его любят за ностальгию и уникальный звук." },
      { text: "Известные исполнители: Anamanaguchi, Chipzel, Sabrepulse." },
      { text: "Этот стиль часто используют в инди-играх и ретро-проектах." },
      { text: "А ты бы слушал chiptune во время игры или просто ради настроения старых игр?" },
    ],
  },
  {
    slug: "kpop",
    title: "K-pop",
    slides: [
      { text: "Представь: яркая сцена, мощный танец и музыка, которая сразу цепляет… это k-pop." },
      { text: "K-pop появился в Южной Корее и быстро стал мировым феноменом." },
      { text: "Этот стиль смешивает поп, хип-хоп, электронную музыку и даже рок." },
      { text: "Главный акцент — на запоминающихся припевах и резких сменах частей трека." },
      { text: "Используются синтезаторы, мощные биты и вокал с идеальной обработкой." },
      { text: "В k-pop музыка всегда связана с танцем и визуальным шоу." },
      { text: "Каждый трек как маленький спектакль с настроением и историей." },
      { text: "Известные исполнители: BTS, BLACKPINK, EXO." },
      { text: "K-pop звучит в клипах, на концертах и в соцсетях по всему миру." },
      { text: "Главная цель — чтобы ты сразу захотел переслушать ещё раз." },
      { text: "А ты бы больше смотрел клипы или просто слушал музыку?" },
    ],
  },
  {
    slug: "afroperc",
    title: "Afro percussion",
    slides: [
      { text: "Представь: вокруг тебя круг людей, и каждый играет свой ритм… это afro percussion." },
      { text: "Этот стиль вырос из традиционной музыки Африки, где ритм — это язык." },
      { text: "Главные инструменты — барабаны: джембе, конги и другие виды перкуссии." },
      { text: "Каждый инструмент играет свой рисунок, и вместе они создают сложный ритм." },
      { text: "Музыка как будто разговаривает — один ритм отвечает другому." },
      { text: "Здесь почти нет мелодии, главное — движение и пульс." },
      { text: "Afro percussion повлиял на джаз, поп и современную танцевальную музыку." },
      { text: "Такие ритмы часто используют на фестивалях и в танцевальных кругах." },
      { text: "Эта музыка чувствуется телом, а не только слышится." },
      { text: "Иногда кажется, что ритм бесконечный и живой." },
      { text: "А ты бы попробовал повторить такой ритм руками?" },
    ],
  },
  {
    slug: "celtic",
    title: "Celtic",
    slides: [
      { text: "Представь: туман, холмы и ветер, который приносит старые мелодии… это celtic." },
      { text: "Кельтская музыка пришла из Ирландии и Шотландии и передавалась из поколения в поколение." },
      { text: "Главные инструменты — скрипка, флейта, волынка и арфа." },
      { text: "Мелодии часто звучат как сказки или древние легенды." },
      { text: "Ритмы могут быть быстрыми для танцев или медленными и волшебными." },
      { text: "Эта музыка часто сопровождает народные праздники и танцы." },
      { text: "Celtic используют в фильмах и играх, чтобы создать ощущение магии." },
      { text: "Известные исполнители: Enya, The Chieftains, Loreena McKennitt." },
      { text: "Когда слушаешь, кажется, что ты попал в другую эпоху." },
      { text: "Это музыка про природу, историю и легенды." },
      { text: "А ты бы слушал celtic как сказку или как музыку для путешествия?" },
    ],
  },
  {
    slug: "latin",
    title: "Latin",
    slides: [
      { text: "Представь: жаркий вечер, музыка играет, и все вокруг начинают танцевать… это latin." },
      { text: "Latin музыка пришла из стран Латинской Америки и вобрала в себя много разных традиций." },
      { text: "Главное здесь — ритм: яркий, быстрый и очень заразительный." },
      { text: "Используются барабаны, конги, маракасы и гитары." },
      { text: "Мелодии часто звучат весело и энергично." },
      { text: "Эта музыка почти всегда связана с танцами: сальса, бачата, румба." },
      { text: "Latin создаёт ощущение праздника, даже если ты просто стоишь." },
      { text: "Известные исполнители: Shakira, Ricky Martin, Bad Bunny." },
      { text: "Она звучит на вечеринках, в путешествиях и на улицах городов." },
      { text: "Эта музыка не даёт сидеть спокойно." },
      { text: "А ты бы сразу пошёл танцевать или сначала посмотрел на других?" },
    ],
  },
  {
    slug: "cartoon",
    title: "Cartoon",
    slides: [
      { text: "Представь: герой подскальзывается на банане — и музыка сразу делает 'плюх!'… это cartoon." },
      { text: "Cartoon музыка появилась в мультфильмах, чтобы подчёркивать каждое действие." },
      { text: "Здесь звуки могут быть смешными, резкими и неожиданными." },
      { text: "Используются пианино, ударные, духовые и куча эффектов." },
      { text: "Музыка может буквально 'рисовать' движение." },
      { text: "Каждый звук — это реакция: прыжок, падение, удивление." },
      { text: "Cartoon стиль помогает сделать сцену смешной или динамичной." },
      { text: "Его часто используют в анимации, играх и детских видео." },
      { text: "Он может быть очень быстрым и хаотичным." },
      { text: "Главная задача — усилить эмоцию." },
      { text: "А ты бы смог озвучить шаги героя такими звуками?" },
    ],
  },
  {
    slug: "rock",
    title: "Rock",
    slides: [
      { text: "Представь: сцена, громкие гитары и толпа, которая кричит вместе с музыкой… это rock." },
      { text: "Rock появился в 1950-х и быстро стал символом свободы и протеста." },
      { text: "Главные инструменты — электрогитара, бас и барабаны." },
      { text: "Гитара часто играет мощные риффы — короткие запоминающиеся куски." },
      { text: "Барабаны делают музыку громкой и энергичной." },
      { text: "Rock может быть разным: от спокойного до очень тяжёлого." },
      { text: "Этот стиль часто связан с живыми концертами и выступлениями." },
      { text: "Известные группы: Queen, Nirvana, AC/DC." },
      { text: "Rock звучит на сценах, в фильмах и в наушниках, когда нужна энергия." },
      { text: "Это музыка, которая даёт почувствовать силу." },
      { text: "А ты бы подпевал или просто слушал и качал головой?" },
    ],
  },
  {
    slug: "classic",
    title: "Classic",
    slides: [
      { text: "Представь: огромный зал, десятки музыкантов и звук, который заполняет всё пространство… это classical music." },
      { text: "Классическая музыка появилась сотни лет назад и развивалась в Европе." },
      { text: "Главные инструменты — скрипки, фортепиано, духовые и целый оркестр." },
      { text: "Здесь нет битов, как в современной музыке — всё строится на мелодии и гармонии." },
      { text: "Музыка может быть тихой, нежной или наоборот очень мощной и драматичной." },
      { text: "Каждое произведение как история без слов." },
      { text: "Композиторы писали музыку, чтобы передать эмоции и идеи." },
      { text: "Известные композиторы: Mozart, Beethoven, Bach." },
      { text: "Классическая музыка звучит в концертах, фильмах и даже в играх." },
      { text: "Она учит слушать детали и чувствовать глубину." },
      { text: "А ты бы слушал классику, чтобы расслабиться или чтобы почувствовать что-то сильное?" },
    ],
  },
  {
    slug: "dance",
    title: "Dance",
    slides: [
      { text: "Представь: музыка включается — и тело сразу хочет двигаться… это dance." },
      { text: "Dance музыка появилась, чтобы люди танцевали и чувствовали ритм вместе." },
      { text: "Главное здесь — чёткий бит и простая, запоминающаяся мелодия." },
      { text: "Используются синтезаторы, электронные звуки и мощные ударные." },
      { text: "Музыка строится так, чтобы ты не останавливался." },
      { text: "Часто в треках есть 'дроп' — момент, когда энергия резко взлетает." },
      { text: "Dance объединяет людей на танцполе." },
      { text: "Известные артисты: Calvin Harris, Avicii, Tiësto." },
      { text: "Этот стиль звучит в клубах, на вечеринках и фестивалях." },
      { text: "Главная цель — движение и энергия." },
      { text: "А ты бы танцевал сразу или сначала послушал пару секунд?" },
    ],
  },
  {
    slug: "spiritual",
    title: "Spiritual",
    slides: [
      { text: "Представь: тихое пространство, где каждый звук будто дышит… это spiritual." },
      { text: "Spiritual музыка связана с медитацией, религией и внутренним состоянием." },
      { text: "Здесь часто звучат хоры, протяжные голоса и спокойные инструменты." },
      { text: "Музыка медленная и повторяющаяся, чтобы успокоить мысли." },
      { text: "Иногда используются колокольчики, гонги или природные звуки." },
      { text: "Главная цель — не развлекать, а погружать внутрь себя." },
      { text: "Такая музыка помогает сосредоточиться и расслабиться." },
      { text: "Она звучит в медитациях, йоге и тихих пространствах." },
      { text: "Spiritual — это больше про ощущение, чем про мелодию." },
      { text: "Музыка как будто замедляет время." },
      { text: "А ты бы включил её, чтобы успокоиться или просто побыть в тишине?" },
    ],
  },
  ];

export const musicStyles_i18n = {
  en: [
    { slug: "lofi", title: "Lo-fi chill", description: "Soft beats, cozy chords, and music for calm focus.", slides: [
      { text: "Lo-fi sounds soft and cozy, with warm beats, jazzy chords, and a gentle layer of background noise." },
      { text: "People often play it while studying, reading, or drawing because it helps them stay focused." },
      { text: "Imagine this: rain outside the window, you sitting with a laptop, and the whole world becoming a little quieter... that is lo-fi." },
      { text: "Lo-fi grew out of 90s hip-hop, when musicians started making music for calm moods and concentration." },
      { text: "Its name means 'low fidelity' — the sound is made a little rough on purpose, almost like an old cassette." },
      { text: "The main instrument is the beat: soft, slow, and very steady, with no sharp hits." },
      { text: "Piano, guitar, or jazzy chords are often added so the music feels warm and cozy." },
      { text: "Background sounds like rain, vinyl crackle, or room noise make the atmosphere feel alive." },
      { text: "Lo-fi almost never distracts you, which is why people listen to it while studying or working." },
      { text: "This style became popular thanks to endless music streams, like 'lofi girl'." },
      { text: "In lo-fi, the mood matters more than musical complexity — everything should sound simple and calm." },
      { text: "Famous artists include Nujabes, J Dilla, and Idealism." },
      { text: "Lo-fi is music that does not demand attention, but makes any activity feel nicer." },
      { text: "Where would you play lo-fi: while studying, before sleep, or just to feel cozy?" },
    ]},
    { slug: "bossa", title: "Bossa nova", description: "Warm Brazilian music with smooth guitar and a gentle sway.", slides: [
      { text: "Bossa nova was born in Brazil and loves soft guitar, light percussion, and the feeling of a warm evening." },
      { text: "It feels relaxed, but it still swings, almost like walking beside the sea." },
      { text: "Imagine a warm evening, the ocean, and you walking barefoot on the sand... that is what bossa nova sounds like." },
      { text: "Bossa nova appeared in Brazil in the late 1950s as a softer version of samba." },
      { text: "Musicians wanted to make music calmer and more intimate, for smaller spaces." },
      { text: "The main instrument is the classical guitar, playing a smooth and swaying rhythm." },
      { text: "Light drums, piano, and a soft almost-whispered vocal are also common." },
      { text: "The rhythm of bossa nova feels like it is gently rocking, like a walk by the sea." },
      { text: "This style quickly became popular all over the world because of its lightness." },
      { text: "Its most famous song is 'The Girl from Ipanema'." },
      { text: "Major artists include Joao Gilberto, Antonio Carlos Jobim, and Stan Getz." },
      { text: "Bossa nova often plays in cafes, films, and quiet evening moments." },
      { text: "This music does not need to be loud — it works through mood and atmosphere." },
      { text: "Where would you listen to bossa nova: on vacation, at home with tea, or on the road?" },
    ]},
    { slug: "synthwave", title: "Synthwave", description: "Neon synthesizers, retro moods, and night-drive energy.", slides: [
      { text: "Synthwave is inspired by 1980s films and games, so it is full of glowing synths and retro color." },
      { text: "It often sounds like driving through a neon city at night." },
      { text: "Imagine the night, a neon city, and you racing down a highway... that is the world of synthwave." },
      { text: "Synthwave is inspired by the music and films of the 1980s, especially science fiction." },
      { text: "The style appeared later as nostalgia for the era of cassettes, arcades, and neon lights." },
      { text: "The main instrument is the synthesizer, which creates bright, glowing sounds." },
      { text: "Electronic drums and a powerful rhythm are also used, like in movie soundtracks." },
      { text: "The music often feels like driving at night through a neon city." },
      { text: "Synthwave is often instrumental, though atmospheric vocals sometimes appear." },
      { text: "The style became popular through games, films, and YouTube videos with retro aesthetics." },
      { text: "Famous artists include Kavinsky, The Midnight, and Perturbator." },
      { text: "Synthwave is often used in games, trailers, and background music for videos." },
      { text: "It is not only about sound, but also about a whole visual world: neon, sunsets, and retro technology." },
      { text: "Would you turn on synthwave in a game, in a car, or just to feel like a movie hero?" },
    ]},
    { slug: "funk", title: "Funk", description: "Springy bass, sharp rhythm, and instant dance energy.", slides: [
      { text: "Funk lives on groove: the bass bounces, the guitar snaps, and the drums keep everything moving." },
      { text: "Its main job is simple: to make your body catch the rhythm on its own." },
      { text: "Imagine walking down the street and suddenly your feet start moving on their own... that means funk just started." },
      { text: "Funk appeared in the United States in the 1960s, when musicians made rhythm the main hero of the music." },
      { text: "The main instrument is the bass guitar, playing springy and very noticeable lines." },
      { text: "In funk, the guitar often does not sing — it snaps with short rhythmic sounds." },
      { text: "The drums play tightly and dry so the whole track stands on groove." },
      { text: "Funk is all about groove: the music seems to bounce and push your body to move." },
      { text: "This style became the foundation for disco, hip-hop, and many modern genres." },
      { text: "Famous artists include James Brown, Parliament-Funkadelic, and Prince." },
      { text: "Funk often plays on dance floors, in movies, and anywhere energy and motion are needed." },
      { text: "This music does not ask — it makes you move." },
      { text: "Would you start dancing right away, or first pretend you are holding back?" },
    ]},
    { slug: "house", title: "House", description: "A steady dance pulse with club energy.", slides: [
      { text: "House is built on a stable beat that keeps going and keeps the dance mood alive." },
      { text: "Melodies and vocal fragments change slowly so the motion never really stops." },
      { text: "Imagine a dark club, flashing lights, and a beat pounding like a heart... that is house." },
      { text: "House appeared in the 1980s in Chicago, when DJs started making music for parties." },
      { text: "Its main element is the steady 'thump-thump-thump-thump' beat that never really stops." },
      { text: "On top of that beat, simple melodies, vocal fragments, and synthesizers are added." },
      { text: "The music changes gradually, not sharply, so people keep dancing." },
      { text: "House creates the feeling of endless motion, as if the track might never end." },
      { text: "This style became the foundation of club culture around the world." },
      { text: "Famous artists include Frankie Knuckles, Daft Punk, and David Guetta." },
      { text: "House is most often heard in clubs, festivals, and parties." },
      { text: "Its main job is to keep you inside the rhythm as long as possible." },
      { text: "Could you dance to house for a whole hour without stopping?" },
    ]},
    { slug: "reggae", title: "Reggae", description: "Relaxed rhythm, warm bass, and sunny sway.", slides: [
      { text: "Reggae is easy to spot because of its relaxed rhythm and accents on the weaker beat." },
      { text: "That makes the music feel like it is rocking gently from side to side." },
      { text: "Imagine sunshine, the sea, and a light breeze... and music gently swaying with you — that is reggae." },
      { text: "Reggae appeared in Jamaica in the 1960s and quickly became the voice of the island's culture and mood." },
      { text: "The main rhythm in reggae is unusual: the accent falls on the weak beat, not the strong one." },
      { text: "Because of that, the music seems to sway from side to side." },
      { text: "The bass in reggae is deep and warm, creating the foundation of the whole track." },
      { text: "The guitar plays short accents, while the drums keep a calm rhythm." },
      { text: "Reggae often carries ideas of freedom, peace, and calm." },
      { text: "The most famous artist is Bob Marley." },
      { text: "This music is heard on beaches, on trips, and in moments of rest." },
      { text: "Reggae does not rush — it teaches you to slow down." },
      { text: "Would you listen to reggae lying on a beach or just to relax at home?" },
    ]},
    { slug: "ambient", title: "Ambient", description: "A space of long sounds and very soft transitions.", slides: [
      { text: "Ambient almost never rushes: atmosphere, air, and long floating sounds matter more than strong rhythm." },
      { text: "People use it to relax, imagine places, or stay inside a certain mood." },
      { text: "Imagine being in a huge space where sounds do not hurry but slowly drift around you... that is ambient." },
      { text: "Ambient appeared in the 1970s, when musicians decided to make music not for rhythm, but for atmosphere." },
      { text: "There are almost no drums here — the main thing is long, stretching sounds." },
      { text: "Synthesizers, echo effects, and recordings of environmental sounds are often used." },
      { text: "The music feels like it is creating a space rather than a melody." },
      { text: "Ambient can be listened to, or simply lived inside, like a background world." },
      { text: "This style is often used in films, games, and meditation." },
      { text: "Famous artists include Brian Eno, Aphex Twin, and Stars of the Lid." },
      { text: "Ambient can help you focus or completely relax." },
      { text: "Sometimes it feels like the music is not changing at all — and that is part of its magic." },
      { text: "Would you play ambient for sleep, work, or just to dissolve into sound?" },
    ]},
    { slug: "jazzhop", title: "Jazzhop", description: "Jazz colors mixed with a soft modern beat.", slides: [
      { text: "Jazzhop combines jazz instruments and chords with a smooth hip-hop beat." },
      { text: "The result feels great for walks, studying, and calm city evenings." },
      { text: "Imagine a cozy cafe, soft light, and someone playing jazz... but with a modern beat — that is jazzhop." },
      { text: "Jazzhop appeared as a blend of jazz and hip-hop, joining the old and the new." },
      { text: "From jazz it took live instruments and complex chords." },
      { text: "From hip-hop it took a calm, swaying beat." },
      { text: "You often hear piano, saxophone, double bass, and soft drums." },
      { text: "The music feels like an evening walk through the city." },
      { text: "Jazzhop is perfect for studying, reading, or drawing." },
      { text: "Famous artists include Nujabes, Jinsang, and Tomppabeats." },
      { text: "This style often appears in 'chill' and 'study beats' playlists." },
      { text: "It relaxes you and still keeps a gentle rhythm." },
      { text: "Would you play jazzhop at home, in headphones outside, or while studying?" },
    ]},
    { slug: "chiptune", title: "Chiptune", description: "Pixel-like game sounds turned into music.", slides: [
      { text: "Chiptune grew out of old console and video game music built from simple electronic sounds." },
      { text: "It feels bright, quick, and playful, like a pixel world coming alive." },
      { text: "Imagine turning on an old game console and the music instantly becoming pixelated... that is chiptune." },
      { text: "Chiptune came from the music of old video games from the 80s and 90s." },
      { text: "Back then computers had very little power, so the sounds were simple." },
      { text: "Basic waveforms were used: beeps, clicks, and short notes." },
      { text: "From those simple sounds, fast and bright melodies were created." },
      { text: "The music often feels energetic and a little toy-like." },
      { text: "Chiptune became its own style even after technology became much more powerful." },
      { text: "People love it for its nostalgia and unique sound." },
      { text: "Famous artists include Anamanaguchi, Chipzel, and Sabrepulse." },
      { text: "This style is often used in indie games and retro projects." },
      { text: "Would you listen to chiptune while gaming or just for the old-game mood?" },
    ]},
    { slug: "kpop", title: "K-pop", description: "Bright pop, dance energy, and dramatic transitions.", slides: [
      { text: "K-pop loves mixing pop, rap, electronics, and huge choruses inside one track." },
      { text: "It works together with dance, stage performance, and a strong visual style." },
      { text: "Imagine a bright stage, powerful choreography, and music that grabs you right away... that is K-pop." },
      { text: "K-pop started in South Korea and quickly became a global phenomenon." },
      { text: "This style mixes pop, hip-hop, electronic music, and even rock." },
      { text: "Its main focus is catchy choruses and sharp changes between parts of a track." },
      { text: "Synthesizers, powerful beats, and polished vocals are used all the time." },
      { text: "In K-pop, the music is always tied to dance and visual performance." },
      { text: "Each track feels like a small show with its own mood and story." },
      { text: "Famous artists include BTS, BLACKPINK, and EXO." },
      { text: "K-pop is heard in music videos, concerts, and social media all over the world." },
      { text: "Its main goal is to make you want to replay it right away." },
      { text: "Would you rather watch the videos or just listen to the music?" },
    ]},
    { slug: "afroperc", title: "Afro percussion", description: "Rhythm music where drums seem to talk to each other.", slides: [
      { text: "Afro percussion is built around drums and percussion, with each layer playing its own rhythmic pattern." },
      { text: "You feel this music with your body as much as with your ears." },
      { text: "Imagine a circle of people around you, each playing their own rhythm... that is afro percussion." },
      { text: "This style grew from traditional African music, where rhythm is a language." },
      { text: "The main instruments are drums: djembe, congas, and many other kinds of percussion." },
      { text: "Each instrument plays its own pattern, and together they create a complex rhythm." },
      { text: "The music seems to talk — one rhythm answers another." },
      { text: "There is almost no melody here; the main thing is movement and pulse." },
      { text: "Afro percussion influenced jazz, pop, and modern dance music." },
      { text: "These rhythms are often used at festivals and in dance circles." },
      { text: "This is music you feel with your body, not only hear with your ears." },
      { text: "Sometimes it feels like the rhythm is endless and alive." },
      { text: "Would you try to repeat such a rhythm with your hands?" },
    ]},
    { slug: "celtic", title: "Celtic", description: "Old melodies, flutes, fiddles, and a legendary mood.", slides: [
      { text: "Celtic music often feels like a story world, with flutes, fiddles, and harps shaping old legends." },
      { text: "It can sound dance-like or magical, almost like wind over hills." },
      { text: "Imagine mist, hills, and wind carrying ancient melodies... that is celtic music." },
      { text: "Celtic music came from Ireland and Scotland and was passed down from generation to generation." },
      { text: "The main instruments are fiddle, flute, bagpipes, and harp." },
      { text: "The melodies often sound like fairy tales or ancient legends." },
      { text: "The rhythms can be fast for dancing or slow and magical." },
      { text: "This music often accompanies folk celebrations and dances." },
      { text: "Celtic music is used in films and games to create a feeling of magic." },
      { text: "Famous artists include Enya, The Chieftains, and Loreena McKennitt." },
      { text: "When you listen to it, it feels as if you have stepped into another era." },
      { text: "It is music about nature, history, and legends." },
      { text: "Would you listen to celtic music like a fairy tale or like a soundtrack for a journey?" },
    ]},
    { slug: "latin", title: "Latin", description: "Warm music with bright percussion and festive movement.", slides: [
      { text: "Latin music loves lively rhythm, warm bass, and percussion that immediately makes you want to move." },
      { text: "Many genres live inside it, but warmth, celebration, and energy connect them." },
      { text: "Imagine a hot evening, music playing, and everyone around you starting to dance... that is latin music." },
      { text: "Latin music comes from countries in Latin America and absorbed many different traditions." },
      { text: "The main thing here is rhythm: bright, fast, and extremely contagious." },
      { text: "Drums, congas, maracas, and guitars are often used." },
      { text: "The melodies often sound joyful and energetic." },
      { text: "This music is almost always linked to dance: salsa, bachata, rumba." },
      { text: "Latin creates a feeling of celebration even if you are just standing still." },
      { text: "Famous artists include Shakira, Ricky Martin, and Bad Bunny." },
      { text: "It is heard at parties, while traveling, and in city streets." },
      { text: "This music does not let you sit still." },
      { text: "Would you go dance right away or first watch the others?" },
    ]},
    { slug: "cartoon", title: "Cartoon", description: "Bouncy sounds for jokes, chases, and surprises.", slides: [
      { text: "Cartoon music helps show laughter, running, surprise, and comedy through quick musical accents." },
      { text: "That is why it works so well in animation and playful scenes." },
      { text: "Imagine a character slipping on a banana peel and the music going 'splat!' right away... that is cartoon music." },
      { text: "Cartoon music appeared in animation to highlight every action on screen." },
      { text: "The sounds can be funny, sharp, and unexpected." },
      { text: "Piano, percussion, brass, and lots of sound effects are used." },
      { text: "The music can literally draw movement." },
      { text: "Each sound is a reaction: a jump, a fall, a surprise." },
      { text: "The cartoon style helps make a scene funny or dynamic." },
      { text: "It is often used in animation, games, and children's videos." },
      { text: "It can be very fast and chaotic." },
      { text: "Its main job is to strengthen the emotion." },
      { text: "Could you make footsteps for a cartoon hero with sounds like that?" },
    ]},
    { slug: "rock", title: "Rock", description: "Guitars, drums, and a bold stage presence.", slides: [
      { text: "Rock loves loud drums, electric guitars, and the energy that pushes a song forward." },
      { text: "People often connect it with freedom, live concerts, and a strong character." },
      { text: "Imagine a stage, loud guitars, and a crowd shouting along with the music... that is rock." },
      { text: "Rock appeared in the 1950s and quickly became a symbol of freedom and protest." },
      { text: "The main instruments are electric guitar, bass, and drums." },
      { text: "The guitar often plays powerful riffs — short memorable phrases." },
      { text: "The drums make the music loud and energetic." },
      { text: "Rock can be very different: from calm to extremely heavy." },
      { text: "This style is strongly connected with live concerts and performances." },
      { text: "Famous bands include Queen, Nirvana, and AC/DC." },
      { text: "Rock is heard on stages, in movies, and in headphones when energy is needed." },
      { text: "It is music that lets you feel strength." },
      { text: "Would you sing along or just listen and nod your head?" },
    ]},
    { slug: "classic", title: "Classical", description: "An orchestra, big feelings, and stories without words.", slides: [
      { text: "Classical music often uses an orchestra, where each instrument helps tell part of the story." },
      { text: "It can feel grand, tender, or dramatic even without any lyrics." },
      { text: "Classical music is often built around an orchestra, where every instrument has an important role." },
      { text: "It can be very calm or very dramatic, telling a story without any words." },
      { text: "Classical music appeared hundreds of years ago and developed in Europe." },
      { text: "The main instruments are violins, piano, wind instruments, and full orchestras." },
      { text: "There are no beats like in modern music — everything is built on melody and harmony." },
      { text: "Music can be very soft and gentle or powerful and dramatic." },
      { text: "Each piece feels like a story without words." },
      { text: "Composers wrote music to express emotions and ideas." },
      { text: "Famous composers include Mozart, Beethoven, and Bach." },
      { text: "Classical music is heard in concerts, films, and even games." },
      { text: "It teaches you to notice details and feel depth." },
      { text: "Would you listen to classical music to relax or to feel something strong?" },
    ]},
    { slug: "dance", title: "Dance", description: "Clear beat and music made for movement.", slides: [
      { text: "Dance music does everything it can to make you catch the beat right away." },
      { text: "Its goal is simple: the track starts and your body wants to move." },
      { text: "Dance music is made so that your body catches the rhythm on its own: a clear beat, a bright chorus, and lots of energy." },
      { text: "The main goal is simple: movement should begin almost as soon as the track starts." },
      { text: "Dance music appeared to make people move and feel rhythm together." },
      { text: "The main thing here is a clear beat and a simple, catchy melody." },
      { text: "Synthesizers, electronic sounds, and strong drums are used." },
      { text: "The music is built so you do not want to stop moving." },
      { text: "Many tracks have a 'drop' — a moment when the energy suddenly jumps." },
      { text: "Dance brings people together on the dance floor." },
      { text: "Famous artists include Calvin Harris, Avicii, and Tiësto." },
      { text: "This style is played in clubs, parties, and festivals." },
      { text: "The main goal is movement and energy." },
      { text: "Would you start dancing right away or wait a few seconds first?" },
    ]},
    { slug: "spiritual", title: "Spiritual", description: "Calm, long tones, and inner space.", slides: [
      { text: "Spiritual music leans toward calmness, with choirs, long notes, and a soft atmosphere." },
      { text: "People listen to it to slow down, focus, or feel the quiet inside the music." },
      { text: "Spiritual music reaches toward calmness, choirs, long sounds, and a sense of inner space." },
      { text: "It can help you focus, slow down, and hear not only rhythm, but also the mood of silence." },
      { text: "Spiritual music is connected to meditation, religion, and inner feelings." },
      { text: "It often includes choirs, long voices, and soft instruments." },
      { text: "The music is slow and repeating to calm your thoughts." },
      { text: "Sometimes bells, gongs, or nature sounds are used." },
      { text: "The goal is not to entertain, but to take you inside yourself." },
      { text: "It helps you focus and relax." },
      { text: "It is often used in meditation, yoga, and quiet spaces." },
      { text: "Spiritual music is more about feeling than melody." },
      { text: "It can make time feel slower." },
      { text: "Would you use it to calm down or just sit in silence?" },
    ]},
  ],
  he: [
    { slug: "lofi", title: "לואו-פיי צ'יל", description: "ביטים רכים, אקורדים נעימים ומוזיקה לריכוז רגוע.", slides: [
      { text: "לואו-פיי נשמע רך ונעים, עם ביטים חמימים, אקורדים בסגנון ג'אז ורעש רקע עדין." },
      { text: "הרבה אנשים שומעים אותו בזמן לימוד, קריאה או ציור כי הוא עוזר להתרכז." },
      { text: "דמייני: גשם בחוץ, את יושבת עם מחשב נייד, והעולם נהיה קצת יותר שקט... זה בדיוק לואו-פיי." },
      { text: "לואו-פיי צמח מההיפ-הופ של שנות התשעים, כשמוזיקאים התחילו ליצור מוזיקה לרוגע ולריכוז." },
      { text: "השם שלו אומר 'נאמנות נמוכה' — הסאונד נעשה בכוונה מעט מחוספס, כמעט כמו קסטה ישנה." },
      { text: "הכלי המרכזי הוא הביט: רך, איטי ויציב מאוד, בלי מכות חדות." },
      { text: "לעיתים מוסיפים פסנתר, גיטרה או אקורדים של ג'אז כדי שהמוזיקה תישמע חמימה ונעימה." },
      { text: "צלילי רקע כמו גשם, חריקות של ויניל או רעש של חדר נותנים לאווירה חיים." },
      { text: "לואו-פיי כמעט אף פעם לא מסיח, ולכן שומעים אותו בזמן לימודים או עבודה." },
      { text: "הסגנון הזה נהיה פופולרי בזכות שידורי מוזיקה אינסופיים, כמו 'lofi girl'." },
      { text: "בלואו-פיי מצב הרוח חשוב יותר ממורכבות מוזיקלית — הכול צריך להישמע פשוט ורגוע." },
      { text: "אמנים מוכרים: Nujabes, J Dilla ו-Idealism." },
      { text: "לואו-פיי היא מוזיקה שלא דורשת תשומת לב, אבל הופכת כל עיסוק לנעים יותר." },
      { text: "איפה היית שומעת לואו-פיי: בזמן לימודים, לפני השינה או סתם בשביל להרגיש נעים?" },
    ]},
    { slug: "bossa", title: "בוסה נובה", description: "מוזיקה ברזילאית חמימה עם גיטרה חלקה וקצב מתנדנד.", slides: [
      { text: "בוסה נובה נולדה בברזיל ואוהבת גיטרה רכה, כלי הקשה עדינים והרגשה של ערב חמים." },
      { text: "היא רגועה, אבל עדיין מתנדנדת, כמעט כמו הליכה ליד הים." },
      { text: "דמייני ערב חמים, אוקיינוס, ואת הולכת יחפה על החול... ככה נשמעת בוסה נובה." },
      { text: "בוסה נובה הופיעה בברזיל בסוף שנות החמישים כגרסה רכה יותר של סמבה." },
      { text: "מוזיקאים רצו ליצור מוזיקה רגועה ואינטימית יותר, שמתאימה למקומות קטנים." },
      { text: "הכלי המרכזי הוא גיטרה קלאסית שמנגנת קצב חלק ומתנדנד." },
      { text: "נפוצים גם תופים עדינים, פסנתר ושירה רכה שכמעט לוחשת." },
      { text: "הקצב של בוסה נובה כאילו מתנדנד ויוצר תחושה של הליכה ליד הים." },
      { text: "הסגנון הזה הפך מהר לפופולרי בכל העולם בזכות הקלילות שלו." },
      { text: "השיר המפורסם ביותר הוא 'The Girl from Ipanema'." },
      { text: "אמנים מרכזיים: Joao Gilberto, Antonio Carlos Jobim ו-Stan Getz." },
      { text: "בוסה נובה נשמעת הרבה בבתי קפה, בסרטים ובערבים רגועים." },
      { text: "המוזיקה הזאת לא צריכה ווליום חזק — היא פועלת דרך מצב רוח ואווירה." },
      { text: "איפה היית שומעת בוסה נובה: בחופשה, בבית עם תה או בדרך?" },
    ]},
    { slug: "synthwave", title: "סינת'ווייב", description: "סינתיסייזרים ניאוניים, אווירת רטרו ואנרגיית לילה.", slides: [
      { text: "סינת'ווייב שואב השראה מסרטים ומשחקים של שנות השמונים, ולכן מלא בצלילי סינתיסייזר זוהרים." },
      { text: "הרבה פעמים הוא נשמע כמו נסיעה לילית בתוך עיר ניאון." },
      { text: "דמייני לילה, עיר ניאון ואת דוהרת על כביש מהיר... זה העולם של סינת'ווייב." },
      { text: "סינת'ווייב שואב השראה מהמוזיקה ומהסרטים של שנות השמונים, במיוחד ממדע בדיוני." },
      { text: "הסגנון הזה הופיע מאוחר יותר מתוך נוסטלגיה לתקופת הקסטות, המשחקיות ואורות הניאון." },
      { text: "הכלי המרכזי הוא הסינתיסייזר, שיוצר צלילים בהירים ו'זוהרים'." },
      { text: "משתמשים גם בתופים אלקטרוניים ובקצב חזק, כמו בפסי קול של סרטים." },
      { text: "המוזיקה הרבה פעמים נשמעת כאילו את נוסעת בלילה בתוך עיר ניאון." },
      { text: "סינת'ווייב הוא לרוב אינסטרומנטלי, אבל לפעמים מוסיפים שירה אווירתית." },
      { text: "הסגנון נהיה פופולרי בזכות משחקים, סרטים וסרטוני יוטיוב עם אסתטיקת רטרו." },
      { text: "אמנים מוכרים: Kavinsky, The Midnight ו-Perturbator." },
      { text: "סינת'ווייב משמש הרבה במשחקים, בטריילרים ובמוזיקת רקע לסרטונים." },
      { text: "זו לא רק מוזיקה של צליל, אלא גם של עולם חזותי שלם: ניאון, שקיעות וטכנולוגיה רטרואית." },
      { text: "היית מפעילה סינת'ווייב במשחק, במכונית או רק כדי להרגיש גיבורת סרט?" },
    ]},
    { slug: "funk", title: "פאנק", description: "בס קפיצי, קצב חד ומוזיקה שמיד מזיזה את הגוף.", slides: [
      { text: "פאנק חי על גרוב: הבס מקפיץ, הגיטרה נותנת מכות קצרות, והתופים דוחפים קדימה." },
      { text: "המטרה שלו פשוטה: שהגוף יתפוס את הקצב כמעט לבד." },
      { text: "דמייני שאת הולכת ברחוב ופתאום הרגליים מתחילות לזוז לבד... זה אומר שפאנק התחיל." },
      { text: "פאנק הופיע בארצות הברית בשנות השישים, כשמוזיקאים הפכו את הקצב לגיבור הראשי של המוזיקה." },
      { text: "הכלי המרכזי הוא גיטרת הבס, שמנגנת קווים קפיציים ובולטים מאוד." },
      { text: "בפאנק הגיטרה לא ממש 'שרה' — היא כאילו נותנת נקישות קצביות קצרות." },
      { text: "התופים מנגנים מדויק ויבש כדי שכל השיר יישען על הגרוב." },
      { text: "פאנק הוא קודם כול גרוב: מוזיקה שקופצת וגורמת לגוף לזוז." },
      { text: "הסגנון הזה הפך לבסיס של דיסקו, היפ-הופ והרבה ז'אנרים מודרניים." },
      { text: "אמנים מוכרים: James Brown, Parliament-Funkadelic ו-Prince." },
      { text: "פאנק נשמע ברחבות ריקודים, בסרטים ובכל מקום שצריך אנרגיה ותנועה." },
      { text: "המוזיקה הזאת לא מבקשת — היא פשוט מזיזה אותך." },
      { text: "היית מתחילה לרקוד מיד, או קודם מעמידה פנים שאת מחזיקה את עצמך?" },
    ]},
    { slug: "house", title: "האוס", description: "דופק ריקודי יציב עם אנרגיה של מועדון.", slides: [
      { text: "האוס בנוי על ביט יציב שנמשך ומחזיק את תחושת הריקוד לאורך זמן." },
      { text: "המנגינות והקולות משתנים בהדרגה כדי שהתנועה לא תיעצר." },
      { text: "דמייני מועדון חשוך, אורות מהבהבים וביט שפועם כמו לב... זה האוס." },
      { text: "האוס הופיע בשנות השמונים בשיקגו, כשדי-ג'ייז התחילו ליצור מוזיקה למסיבות." },
      { text: "היסוד המרכזי שלו הוא ביט קבוע של 'טאק-טאק-טאק-טאק' שכמעט לא נעצר." },
      { text: "מעל הביט הזה מוסיפים מלודיות פשוטות, קטעי שירה וסינתיסייזרים." },
      { text: "המוזיקה משתנה בהדרגה ולא בחדות, כדי שהאנשים ימשיכו לרקוד." },
      { text: "האוס יוצר תחושה של תנועה אינסופית, כאילו השיר לא עומד להיגמר." },
      { text: "הסגנון הזה הפך ליסוד של תרבות המועדונים בכל העולם." },
      { text: "אמנים מוכרים: Frankie Knuckles, Daft Punk ו-David Guetta." },
      { text: "האוס נשמע בעיקר במועדונים, בפסטיבלים ובמסיבות." },
      { text: "המטרה המרכזית שלו היא להחזיק אותך בתוך הקצב כמה שיותר זמן." },
      { text: "היית מסוגלת לרקוד להאוס שעה שלמה בלי לעצור?" },
    ]},
    { slug: "reggae", title: "רגאיי", description: "קצב רגוע, בס חמים ותנועה שטופת שמש.", slides: [
      { text: "קל לזהות רגאיי בזכות הקצב הרגוע וההדגשים על הפעמה החלשה." },
      { text: "זה גורם למוזיקה להרגיש כאילו היא מתנדנדת מצד לצד." },
      { text: "דמייני שמש, ים ורוח קלה... והמוזיקה מתנדנדת איתך בעדינות — זה רגאיי." },
      { text: "רגאיי הופיע בג'מייקה בשנות השישים והפך מהר לקול של התרבות ושל מצב הרוח של האי." },
      { text: "הקצב המרכזי ברגאיי מיוחד: ההדגשה היא דווקא על הפעמה החלשה." },
      { text: "בגלל זה המוזיקה מרגישה כאילו היא מתנדנדת מצד לצד." },
      { text: "הבס ברגאיי עמוק וחמים, והוא יוצר את הבסיס של כל השיר." },
      { text: "הגיטרה מנגנת הדגשות קצרות, והתופים מחזיקים קצב רגוע." },
      { text: "רגאיי נושא לעיתים קרובות רעיונות של חופש, שלום ורוגע." },
      { text: "האמן המפורסם ביותר הוא Bob Marley." },
      { text: "המוזיקה הזאת נשמעת בחופים, בטיולים וברגעי מנוחה." },
      { text: "רגאיי לא ממהר — הוא מלמד להאט." },
      { text: "היית שומעת רגאיי בשכיבה על חוף הים או פשוט כדי להירגע בבית?" },
    ]},
    { slug: "ambient", title: "אמביינט", description: "מרחב של צלילים ארוכים ומעברים רכים מאוד.", slides: [
      { text: "אמביינט כמעט לא ממהר: האווירה, האוויר והצלילים המתמשכים חשובים בו יותר מהקצב." },
      { text: "שומעים אותו כדי להירגע, לדמיין מקום או פשוט להישאר בתוך מצב רוח מסוים." },
      { text: "דמייני שאת נמצאת במרחב עצום שבו הצלילים לא ממהרים אלא צפים סביבך לאט... זה אמביינט." },
      { text: "אמביינט הופיע בשנות השבעים, כשמוזיקאים החליטו ליצור מוזיקה לא בשביל קצב אלא בשביל אווירה." },
      { text: "כמעט אין כאן תופים — העיקר הוא צלילים ארוכים ונמתחים." },
      { text: "הרבה פעמים משתמשים בסינתיסייזרים, בהדים ובהקלטות של צלילי סביבה." },
      { text: "המוזיקה מרגישה כאילו היא בונה מרחב ולא רק מלודיה." },
      { text: "אפשר להקשיב לאמביינט, ואפשר פשוט לחיות בתוכו כמו בתוך רקע." },
      { text: "הסגנון הזה משמש הרבה בסרטים, במשחקים ובמדיטציה." },
      { text: "אמנים מוכרים: Brian Eno, Aphex Twin ו-Stars of the Lid." },
      { text: "אמביינט יכול לעזור להתרכז או להפך, להירגע לגמרי." },
      { text: "לפעמים נדמה שהמוזיקה בכלל לא משתנה — ודווקא בזה טמון הקסם שלה." },
      { text: "היית מפעילה אמביינט לשינה, לעבודה או רק כדי 'להתמוסס' בתוך צליל?" },
    ]},
    { slug: "jazzhop", title: "ג'אזהופ", description: "צבעים של ג'אז עם ביט מודרני ורך.", slides: [
      { text: "ג'אזהופ מחבר כלי נגינה ואקורדים של ג'אז עם ביט היפ-הופ חלק." },
      { text: "הוא מתאים להליכה, ללימוד ולערב עירוני רגוע." },
      { text: "דמייני בית קפה נעים, אור רך ומישהו שמנגן ג'אז... אבל עם ביט מודרני — זה ג'אזהופ." },
      { text: "ג'אזהופ נולד כשילוב בין ג'אז להיפ-הופ, ומחבר בין ישן לחדש." },
      { text: "מהג'אז הוא לקח כלים חיים ואקורדים מורכבים." },
      { text: "מההיפ-הופ הוא לקח ביט רגוע ומתנדנד." },
      { text: "שומעים בו הרבה פסנתר, סקסופון, קונטרבס ותופים רכים." },
      { text: "המוזיקה מרגישה כמו הליכת ערב בעיר." },
      { text: "ג'אזהופ מתאים מאוד ללימוד, לקריאה או לציור." },
      { text: "אמנים מוכרים: Nujabes, Jinsang ו-Tomppabeats." },
      { text: "הסגנון הזה מופיע הרבה בפלייליסטים של 'chill' ו-'study beats'." },
      { text: "הוא גם מרגיע וגם שומר על קצב עדין." },
      { text: "היית מפעילה ג'אזהופ בבית, באוזניות ברחוב או בזמן לימודים?" },
    ]},
    { slug: "chiptune", title: "צ'יפטיון", description: "צלילי משחקי וידאו ישנים שהפכו למוזיקה.", slides: [
      { text: "צ'יפטיון צמח ממוזיקה של קונסולות ישנות ומשחקים שנבנו מצלילים אלקטרוניים פשוטים." },
      { text: "הוא נשמע צבעוני, מהיר ושובב, כאילו עולם פיקסלים התעורר לחיים." },
      { text: "דמייני שאת מדליקה קונסולה ישנה, והמוזיקה מיד נהיית פיקסלית... זה צ'יפטיון." },
      { text: "צ'יפטיון צמח מתוך המוזיקה של משחקי הווידאו הישנים של שנות השמונים והתשעים." },
      { text: "באותם ימים למחשבים הייתה מעט מאוד עוצמה, ולכן הצלילים היו פשוטים." },
      { text: "השתמשו בגלים בסיסיים: צפצופים, קליקים ותווים קצרים." },
      { text: "מהצלילים הפשוטים האלה יצרו מלודיות מהירות ובהירות." },
      { text: "המוזיקה לרוב נשמעת אנרגטית וקצת 'צעצועית'." },
      { text: "צ'יפטיון הפך לסגנון בפני עצמו גם כשהטכנולוגיה כבר נהייתה חזקה יותר." },
      { text: "אוהבים אותו בגלל הנוסטלגיה והצליל הייחודי שלו." },
      { text: "אמנים מוכרים: Anamanaguchi, Chipzel ו-Sabrepulse." },
      { text: "הסגנון הזה משמש הרבה במשחקי אינדי ובפרויקטים רטרואיים." },
      { text: "היית שומעת צ'יפטיון בזמן משחק או פשוט בשביל האווירה של משחקים ישנים?" },
    ]},
    { slug: "kpop", title: "קיי-פופ", description: "פופ בוהק, אנרגיית ריקוד ומעברים דרמטיים.", slides: [
      { text: "קיי-פופ אוהב לערבב פופ, ראפ, אלקטרוניקה ופזמונים גדולים בתוך שיר אחד." },
      { text: "הוא עובד יחד עם ריקוד, הופעה בימתית ודימוי חזותי חזק." },
      { text: "דמייני במה צבעונית, ריקוד חזק ומוזיקה שתופסת אותך מיד... זה קיי-פופ." },
      { text: "קיי-פופ נולד בדרום קוריאה והפך מהר לתופעה עולמית." },
      { text: "הסגנון הזה מערבב פופ, היפ-הופ, מוזיקה אלקטרונית ואפילו רוק." },
      { text: "הדגש המרכזי הוא על פזמונים קליטים ושינויים חדים בין חלקי השיר." },
      { text: "משתמשים בו בסינתיסייזרים, ביטים חזקים ושירה מלוטשת מאוד." },
      { text: "בקיי-פופ המוזיקה תמיד מחוברת לריקוד ולמופע חזותי." },
      { text: "כל שיר מרגיש כמו מופע קטן עם אווירה וסיפור משלו." },
      { text: "אמנים מוכרים: BTS, BLACKPINK ו-EXO." },
      { text: "קיי-פופ נשמע בקליפים, בהופעות וברשתות חברתיות בכל העולם." },
      { text: "המטרה העיקרית היא שתרצי לשמוע שוב מיד." },
      { text: "היית מעדיפה לראות את הקליפים או פשוט להקשיב למוזיקה?" },
    ]},
    { slug: "afroperc", title: "אפרו פרקשן", description: "מוזיקת קצב שבה התופים כאילו מדברים זה עם זה.", slides: [
      { text: "אפרו פרקשן בנוי סביב תופים וכלי הקשה, כשכל שכבה מנגנת דפוס קצבי משלה." },
      { text: "זו מוזיקה שמרגישים בגוף כמעט כמו ששומעים באוזניים." },
      { text: "דמייני מעגל של אנשים סביבך, וכל אחד מנגן את הקצב שלו... זה אפרו פרקשן." },
      { text: "הסגנון הזה צמח מהמוזיקה המסורתית של אפריקה, שבה הקצב הוא שפה." },
      { text: "הכלים המרכזיים הם תופים: ג'מבה, קונגה וסוגים רבים אחרים של כלי הקשה." },
      { text: "כל כלי מנגן דפוס משלו, וביחד הם יוצרים קצב מורכב." },
      { text: "המוזיקה כאילו מדברת — קצב אחד עונה לאחר." },
      { text: "כמעט אין כאן מלודיה; העיקר הוא תנועה ודופק." },
      { text: "אפרו פרקשן השפיע על ג'אז, פופ ומוזיקת דאנס מודרנית." },
      { text: "את הקצבים האלה שומעים הרבה בפסטיבלים ובמעגלי ריקוד." },
      { text: "זו מוזיקה שמרגישים בגוף, לא רק שומעים באוזניים." },
      { text: "לפעמים נדמה שהקצב אינסופי וחי." },
      { text: "היית מנסה לחזור בידיים על קצב כזה?" },
    ]},
    { slug: "celtic", title: "קלטי", description: "מנגינות עתיקות, חלילים, כינורות ואווירת אגדה.", slides: [
      { text: "מוזיקה קלטית מרגישה לעיתים כמו עולם של סיפור, עם חלילים, כינורות ונבלים." },
      { text: "היא יכולה להיות ריקודית או קסומה, כמעט כמו רוח מעל גבעות." },
      { text: "דמייני ערפל, גבעות ורוח שמביאה איתה מנגינות עתיקות... זו מוזיקה קלטית." },
      { text: "המוזיקה הקלטית הגיעה מאירלנד ומסקוטלנד ועברה מדור לדור." },
      { text: "הכלים המרכזיים הם כינור, חליל, חמת חלילים ונבל." },
      { text: "המלודיות נשמעות לעיתים כמו אגדות או סיפורים קדומים." },
      { text: "הקצבים יכולים להיות מהירים בשביל ריקוד או איטיים וקסומים." },
      { text: "המוזיקה הזאת מלווה לעיתים קרובות חגים עממיים וריקודים." },
      { text: "מוזיקה קלטית משמשת בסרטים ובמשחקים כדי ליצור תחושה של קסם." },
      { text: "אמנים מוכרים: Enya, The Chieftains ו-Loreena McKennitt." },
      { text: "כששומעים אותה, לפעמים מרגישים כאילו נכנסים לתקופה אחרת." },
      { text: "זו מוזיקה על טבע, היסטוריה ואגדות." },
      { text: "היית שומעת מוזיקה קלטית כמו אגדה או כמו פס-קול למסע?" },
    ]},
    { slug: "latin", title: "לטיני", description: "מוזיקה חמימה עם כלי הקשה בולטים ותנועה חגיגית.", slides: [
      { text: "מוזיקה לטינית אוהבת קצב חי, בס חמים וכלי הקשה שמיד גורמים לרצות לזוז." },
      { text: "יש בה הרבה סגנונות, אבל חום, חגיגה ואנרגיה מחברים ביניהם." },
      { text: "דמייני ערב חם, מוזיקה מתנגנת וכולם סביבך מתחילים לרקוד... זו מוזיקה לטינית." },
      { text: "המוזיקה הלטינית הגיעה ממדינות אמריקה הלטינית וספגה לתוכה מסורות רבות ושונות." },
      { text: "הדבר המרכזי כאן הוא הקצב: בהיר, מהיר ומדבק מאוד." },
      { text: "משתמשים הרבה בתופים, קונגות, מרקס וגיטרות." },
      { text: "המלודיות לרוב נשמעות שמחות ואנרגטיות." },
      { text: "המוזיקה הזאת כמעט תמיד קשורה לריקוד: סלסה, בצ'אטה, רומבה." },
      { text: "המוזיקה הלטינית יוצרת תחושה של חגיגה גם אם את רק עומדת." },
      { text: "אמנים מוכרים: Shakira, Ricky Martin ו-Bad Bunny." },
      { text: "היא נשמעת במסיבות, בטיולים וברחובות של ערים." },
      { text: "זו מוזיקה שלא נותנת לשבת בשקט." },
      { text: "היית הולכת לרקוד מיד או קודם מסתכלת על אחרים?" },
    ]},
    { slug: "cartoon", title: "קרטון", description: "צלילים קופצניים לבדיחות, מרדפים והפתעות.", slides: [
      { text: "מוזיקת קרטון עוזרת להראות צחוק, ריצה, הפתעה וקומדיה דרך הדגשות קצרות." },
      { text: "לכן היא עובדת כל כך טוב באנימציה ובסצנות שובבות." },
      { text: "דמייני דמות שמחליקה על קליפת בננה, והמוזיקה מיד עושה 'פלאפ!'... זו מוזיקת קרטון." },
      { text: "מוזיקת קרטון נולדה בסרטים מצוירים כדי להדגיש כל פעולה על המסך." },
      { text: "הצלילים יכולים להיות מצחיקים, חדים ולא צפויים." },
      { text: "משתמשים בפסנתר, בכלי הקשה, בכלי נשיפה והמון אפקטים." },
      { text: "המוזיקה יכולה ממש 'לצייר' תנועה." },
      { text: "כל צליל הוא תגובה: קפיצה, נפילה, הפתעה." },
      { text: "סגנון הקרטון עוזר להפוך סצנה למצחיקה או דינמית." },
      { text: "משתמשים בו הרבה באנימציה, במשחקים ובסרטונים לילדים." },
      { text: "הוא יכול להיות מהיר מאוד וכאוטי." },
      { text: "המטרה המרכזית היא לחזק את הרגש." },
      { text: "היית מצליחה להשמיע צעדים של גיבור מצויר בעזרת צלילים כאלה?" },
    ]},
    { slug: "rock", title: "רוק", description: "גיטרות, תופים ונוכחות בימתית נועזת.", slides: [
      { text: "רוק אוהב תופים חזקים, גיטרות חשמליות ואנרגיה שדוחפת את השיר קדימה." },
      { text: "הרבה אנשים מקשרים אותו לחופש, להופעות חיות ולאופי חזק." },
      { text: "דמייני במה, גיטרות רועמות וקהל שצועק יחד עם המוזיקה... זה רוק." },
      { text: "רוק הופיע בשנות החמישים והפך מהר לסמל של חופש ושל מחאה." },
      { text: "הכלים המרכזיים הם גיטרה חשמלית, בס ותופים." },
      { text: "הגיטרה מנגנת לעיתים קרובות ריפים חזקים — קטעים קצרים שקל לזכור." },
      { text: "התופים הופכים את המוזיקה לרועשת ומלאת אנרגיה." },
      { text: "רוק יכול להיות מאוד שונה: מרגוע ועד כבד מאוד." },
      { text: "הסגנון הזה קשור מאוד להופעות חיות ולבמה." },
      { text: "להקות מוכרות: Queen, Nirvana ו-AC/DC." },
      { text: "רוק נשמע על במות, בסרטים ובאוזניות כשצריך אנרגיה." },
      { text: "זו מוזיקה שנותנת להרגיש כוח." },
      { text: "היית שרה יחד או רק מקשיבה ומניעה את הראש?" },
    ]},
    { slug: "classic", title: "קלאסי", description: "תזמורת, רגשות גדולים וסיפורים בלי מילים.", slides: [
      { text: "מוזיקה קלאסית בנויה לעיתים קרובות על תזמורת, שבה כל כלי מוסיף חלק מהסיפור." },
      { text: "היא יכולה להרגיש חגיגית, עדינה או דרמטית גם בלי מילים בכלל." },
      { text: "מוזיקה קלאסית בנויה לעיתים קרובות סביב תזמורת, שבה לכל כלי יש תפקיד חשוב." },
      { text: "היא יכולה להיות רגועה מאוד או דרמטית מאוד, ולספר סיפור גם בלי מילים." },
      { text: "המוזיקה הקלאסית הופיעה לפני מאות שנים והתפתחה באירופה." },
      { text: "הכלים המרכזיים הם כינורות, פסנתר, כלי נשיפה ותזמורת שלמה." },
      { text: "אין כאן ביטים כמו במוזיקה מודרנית — הכול בנוי על מלודיה והרמוניה." },
      { text: "המוזיקה יכולה להיות עדינה ושקטה או חזקה ודרמטית מאוד." },
      { text: "כל יצירה מרגישה כמו סיפור בלי מילים." },
      { text: "המלחינים כתבו מוזיקה כדי להעביר רגשות ורעיונות." },
      { text: "מלחינים מפורסמים: מוצרט, בטהובן ובאך." },
      { text: "המוזיקה הקלאסית נשמעת בקונצרטים, בסרטים ואפילו במשחקים." },
      { text: "היא מלמדת לשים לב לפרטים ולהרגיש עומק." },
      { text: "היית שומעת מוזיקה קלאסית כדי להירגע או כדי להרגיש משהו חזק?" },
    ]},
    { slug: "dance", title: "דאנס", description: "ביט ברור ומוזיקה שנועדה לתנועה.", slides: [
      { text: "דאנס עושה הכול כדי שתתפסו את הקצב מיד כשהשיר מתחיל." },
      { text: "המטרה שלו פשוטה: להפעיל את הגוף כמעט מהשנייה הראשונה." },
      { text: "מוזיקת דאנס נוצרת כך שהגוף יתפוס את הקצב כמעט לבד: ביט ברור, פזמון חזק והמון אנרגיה." },
      { text: "המטרה כאן פשוטה: שהתנועה תתחיל כמעט מיד כשהשיר מתחיל." },
      { text: "מוזיקת דאנס נוצרה כדי לגרום לאנשים לזוז ולהרגיש את הקצב יחד." },
      { text: "הדבר המרכזי כאן הוא ביט ברור ומלודיה פשוטה שקל לזכור." },
      { text: "משתמשים בסינתיסייזרים, צלילים אלקטרוניים ותופים חזקים." },
      { text: "המוזיקה בנויה כך שלא תרצי להפסיק לזוז." },
      { text: "בהרבה שירים יש 'דרופ' — רגע שבו האנרגיה קופצת בפתאומיות." },
      { text: "דאנס מחבר אנשים יחד ברחבת הריקודים." },
      { text: "אמנים מוכרים: Calvin Harris, Avicii ו-Tiësto." },
      { text: "הסגנון הזה נשמע במועדונים, במסיבות ובפסטיבלים." },
      { text: "המטרה העיקרית היא תנועה ואנרגיה." },
      { text: "היית מתחילה לרקוד מיד או מחכה כמה שניות?" },
    ]},
    { slug: "spiritual", title: "רוחני", description: "שקט, צלילים ארוכים ומרחב פנימי.", slides: [
      { text: "מוזיקה רוחנית נוטה לרוגע, עם מקהלות, צלילים ארוכים ואווירה עדינה." },
      { text: "שומעים אותה כדי להאט, להתרכז או להרגיש את השקט שבתוך המוזיקה." },
      { text: "מוזיקה רוחנית נמשכת אל רוגע, מקהלות, צלילים ארוכים ותחושה של מרחב פנימי." },
      { text: "היא יכולה לעזור להתרכז, להאט ולהקשיב לא רק לקצב אלא גם לשקט שבתוך האווירה." },
      { text: "מוזיקה רוחנית קשורה למדיטציה, דת ותחושות פנימיות." },
      { text: "לעיתים קרובות שומעים בה מקהלות, קולות ארוכים וכלים רגועים." },
      { text: "המוזיקה איטית וחוזרת על עצמה כדי להרגיע את המחשבות." },
      { text: "לפעמים משתמשים בפעמונים, גונגים או צלילי טבע." },
      { text: "המטרה היא לא לבדר, אלא לקחת אותך פנימה." },
      { text: "היא עוזרת להתרכז ולהירגע." },
      { text: "משתמשים בה במדיטציה, ביוגה ובמקומות שקטים." },
      { text: "זו מוזיקה של תחושה יותר מאשר של מלודיה." },
      { text: "היא יכולה לגרום לזמן להרגיש איטי יותר." },
      { text: "היית משתמשת בה כדי להירגע או פשוט לשבת בשקט?" },
    ]},
  ],
};

export function getMusicStyle(lang: "ru" | "en" | "he", slug: string): MusicStyle | null {
  if (lang === "ru") {
    return musicStyles_ru.find((style) => style.slug === slug) ?? null;
  }

  const localized = musicStyles_i18n[lang]?.find((style) => style.slug === slug);
  if (localized) {
    return localized;
  }

  return musicStyles_ru.find((style) => style.slug === slug) ?? null;
}
