import { useEffect, useRef, useState } from "react";
import type { Lang } from "@/i18n";
import { dictionaries } from "@/i18n";
import { SOUND_CODE_DIGITS, STAGE_6_DECODER_DIGITS, type SoundCodeDigit, validateStage6Decoder } from "@/lib/shop/quests/sound-case-001/soundCode";
import { STAGE_6_COORDINATE_PUZZLE } from "@/lib/shop/quests/sound-case-001/scatteredSand";

type Stage6Step="intro"|"decoder"|"success"|"map";
type DecoderAxisProps={label:string;prefix:string;offset:number;values:string[];incorrect:boolean[];activeSlot:number|null;onSelect:(index:number)=>void};

function DecoderAxis({label,prefix,offset,values,incorrect,activeSlot,onSelect}:DecoderAxisProps){
  return <div className="stage-6__coordinate-row" dir="ltr" aria-label={label}><b>{prefix}</b>{Array.from({length:6},(_,localIndex)=>{const index=offset+localIndex;const classes=["stage-6__digit",activeSlot===index?"stage-6__digit--active":"",incorrect[index]?"stage-6__digit--wrong":""].filter(Boolean).join(" ");return <button type="button" key={index} className={classes} onClick={()=>onSelect(index)} aria-pressed={activeSlot===index} aria-label={`${label} ${localIndex+1}`}>{values[index]||<span aria-hidden="true">&nbsp;</span>}</button>;})}<b>{offset===0?"° N":"° E"}</b></div>;
}

export function SoundCodeScene({lang,backgroundUrl,parrotUrls,audioUrls}:{lang:Lang;backgroundUrl:string;parrotUrls:string[];audioUrls:Partial<Record<SoundCodeDigit,string>>;leadName?:string}){
  const soundCase=dictionaries[lang].shop.soundCase;const t=soundCase.stage06;const rtl=lang==="he";const audio=useRef<HTMLAudioElement|null>(null);const stageTop=useRef<HTMLElement|null>(null);const activeSlotRef=useRef<number|null>(0);
  const [step,setStep]=useState<Stage6Step>("intro"),[playing,setPlaying]=useState<number|null>(null),[paused,setPaused]=useState(false),[values,setValues]=useState<string[]>(()=>Array(STAGE_6_DECODER_DIGITS.length).fill("")),[activeSlot,setActiveSlot]=useState<number|null>(0),[incorrect,setIncorrect]=useState<boolean[]>(()=>Array(STAGE_6_DECODER_DIGITS.length).fill(false)),[decodeAttempted,setDecodeAttempted]=useState(false),[copied,setCopied]=useState(false);
  const stop=()=>{if(audio.current){audio.current.onended=null;audio.current.pause();audio.current.currentTime=0;}audio.current=null;setPlaying(null);setPaused(false);};
  useEffect(()=>stop,[]);
  const changeStep=(next:Stage6Step)=>{stop();setCopied(false);setStep(next);window.requestAnimationFrame(()=>stageTop.current?.scrollIntoView({behavior:"smooth",block:"start"}));};
  const selectSlot=(index:number|null)=>{activeSlotRef.current=index;setActiveSlot(index);};
  const enterDigit=(digit:SoundCodeDigit)=>{const currentIndex=activeSlotRef.current;if(step!=="decoder"||currentIndex===null)return;setValues(current=>{const next=current.map((value,index)=>index===currentIndex?String(digit):value);let nextSlot:number|null=null;for(let offset=1;offset<=next.length;offset+=1){const candidate=(currentIndex+offset)%next.length;if(next[candidate]===""){nextSlot=candidate;break;}}selectSlot(nextSlot);return next;});setIncorrect(current=>current.map((value,index)=>index===currentIndex?false:value));setDecodeAttempted(false);};
  const playDigit=(digit:SoundCodeDigit)=>{stop();enterDigit(digit);const url=audioUrls[digit];if(!url)return;const element=new Audio(url);audio.current=element;setPlaying(digit);setPaused(false);element.onended=()=>{setPlaying(null);setPaused(false);};void element.play();};
  const togglePlayback=()=>{const element=audio.current;if(!element)return;if(element.paused){void element.play();setPaused(false);}else{element.pause();setPaused(true);}};
  const replayCurrent=()=>{const element=audio.current;if(!element)return;element.currentTime=0;void element.play();setPaused(false);};
  const checkDecode=()=>{const result=validateStage6Decoder(values);setIncorrect(result.map(value=>!value));setDecodeAttempted(true);if(result.every(Boolean))changeStep("success");};
  const copy=async()=>{try{await navigator.clipboard.writeText(STAGE_6_COORDINATE_PUZZLE.final.clipboard);}catch{const element=document.createElement("textarea");element.value=STAGE_6_COORDINATE_PUZZLE.final.clipboard;document.body.appendChild(element);element.select();document.execCommand("copy");element.remove();}setCopied(true);};
  const complete=values.every(Boolean);
  const mapQuery=encodeURIComponent(STAGE_6_COORDINATE_PUZZLE.final.clipboard);
  return <main ref={stageTop} className="stage-6" lang={lang} dir={rtl?"rtl":"ltr"} style={{backgroundImage:`url(${backgroundUrl})`}}><div className="stage-6__shell"><header><bdi dir="ltr">PARROT SOUND LAB</bdi><span>{t.stageLabel}</span></header>
    {step==="intro"?<section className="stage-6__panel stage-6__intro"><img src={parrotUrls[0]} alt=""/><div><h1>{t.title}</h1><h2>{t.soundWarning}</h2><p>{t.volumeHint}</p><div className="stage-6__actions"><button onClick={()=>playDigit(2)}>{t.testSound}</button><button className="stage-6__primary" onClick={()=>changeStep("decoder")}>{t.start}</button></div></div></section>:null}
    {step==="decoder"?<div className="stage-6__step"><section className="stage-6__panel"><h2>{t.instructionsTitle}</h2><p>{soundCase.stage06InputHint}</p><div className="stage-6__teams"><b>{t.teamTitle}</b><span>{t.teamSmall}</span><span>{t.teamLarge}</span><strong>{t.latitudeTeam}</strong><strong>{t.longitudeTeam}</strong></div></section>
      <section className="stage-6__panel"><h2>{t.codeTitle}</h2><div className="stage-6__code" dir="ltr">{SOUND_CODE_DIGITS.map(item=><button key={item.digit} onClick={()=>playDigit(item.digit)}><span>{item.icon}</span><b>{item.digit}</b><small>{playing===item.digit?(paused?t.playing:t.playing):t.listen}</small><em>{t.digitNames[item.digit]}</em></button>)}</div>{playing!==null?<div className="stage-6__playback" role="group" aria-label={t.playbackControls}><button onClick={togglePlayback}>{paused?t.resume:t.pause}</button><button onClick={replayCurrent}>{t.replay}</button></div>:null}</section>
      <section className="stage-6__panel stage-6__decoder"><h2>{t.decoderTitle}</h2><div className="stage-6__coordinates" dir="ltr"><DecoderAxis label={t.latitude} prefix={STAGE_6_COORDINATE_PUZZLE.latitude.prefix} offset={0} values={values} incorrect={incorrect} activeSlot={activeSlot} onSelect={selectSlot}/><DecoderAxis label={t.longitude} prefix={STAGE_6_COORDINATE_PUZZLE.longitude.prefix} offset={6} values={values} incorrect={incorrect} activeSlot={activeSlot} onSelect={selectSlot}/></div>{decodeAttempted?<p className="stage-6__decode-error" role="alert">{t.decodeError}</p>:null}<button className="stage-6__primary" disabled={!complete} onClick={checkDecode}>{t.decodedAction}</button></section></div>:null}
    {step==="success"?<section className="stage-6__panel stage-6__verified stage-6__step-screen"><h1>{t.decodeSuccess}</h1><div dir="ltr"><strong>{STAGE_6_COORDINATE_PUZZLE.final.latitude}</strong><strong>{STAGE_6_COORDINATE_PUZZLE.final.longitude}</strong></div><button onClick={copy}>{copied?t.copied:t.copy}</button><button className="stage-6__primary" onClick={()=>changeStep("map")}>{soundCase.stage06SuccessNext}</button></section>:null}
    {step==="map"?<section className="stage-6__panel stage-6__earth stage-6__step-screen"><img src={parrotUrls[1]||parrotUrls[0]} alt=""/><div>{t.earthLines.map(line=><p key={line}>{line}</p>)}<h1>{t.findPlace}</h1><div className="stage-6__map-coordinates" dir="ltr"><strong>{STAGE_6_COORDINATE_PUZZLE.final.latitude}</strong><strong>{STAGE_6_COORDINATE_PUZZLE.final.longitude}</strong></div><button onClick={copy}>{copied?t.copied:t.copy}</button><ol>{t.mapSteps.slice(0,4).map(line=><li key={line}>{line}</li>)}</ol><div><a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${mapQuery}`}>{t.googleMaps}</a><a target="_blank" rel="noreferrer" href={`https://earth.google.com/web/search/${mapQuery}`}>{t.googleEarth}</a></div></div></section>:null}
  </div></main>;
}
